'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.17929.
'
Namespace ModelControl

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class model

        Private idField As Decimal

        Private id_secondaryField As String

        Private titleField As String

        Private pathField As path

        Private database_file_nameField As String

        Private command_lineField As String

        Private descriptionField As String

        Private commentsField As String

        Private testsField() As String

        Private updatesField() As updatesUpdate

        Private keywordsField() As String

        Private classificationField As classification

        Private imagesField() As imagesImage

        Private attachmentsField() As attachmentsAttachment

        Private linksField() As linksLink

        Private resultsField() As result

        Private postprocessed_resultsField() As postprocessed_result

        Private excel_resultsField As excel_results

        Private incidentsField() As incidentsIncident

        Private ticketsField() As ticketsTicket

        Private programField As program

        Private target_programField() As target_programProgram

        Private authorField As author

        Private dateField As [date]

        Private run_timeField As run_time

        Private regtest_internal_useField As regtest_internal_use

        Private is_publicField As String

        Private is_bugField As String

        Private statusField As status_model

        Private statusFieldSpecified As Boolean

        Private documentation_statusField As status_documentation

        Private documentation_statusFieldSpecified As Boolean

        '''<remarks/>
        Public Property id() As Decimal
            Get
                Return Me.idField
            End Get
            Set(value As Decimal)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        Public Property id_secondary() As String
            Get
                Return Me.id_secondaryField
            End Get
            Set(value As String)
                Me.id_secondaryField = value
            End Set
        End Property

        '''<remarks/>
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set(value As String)
                Me.titleField = value
            End Set
        End Property

        '''<remarks/>
        Public Property path() As path
            Get
                Return Me.pathField
            End Get
            Set(value As path)
                Me.pathField = value
            End Set
        End Property

        '''<remarks/>
        Public Property database_file_name() As String
            Get
                Return Me.database_file_nameField
            End Get
            Set(value As String)
                Me.database_file_nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property command_line() As String
            Get
                Return Me.command_lineField
            End Get
            Set(value As String)
                Me.command_lineField = value
            End Set
        End Property

        '''<remarks/>
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set(value As String)
                Me.descriptionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property comments() As String
            Get
                Return Me.commentsField
            End Get
            Set(value As String)
                Me.commentsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("test", IsNullable:=False)> _
        Public Property tests() As String()
            Get
                Return Me.testsField
            End Get
            Set(value As String())
                Me.testsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("update", IsNullable:=False)> _
        Public Property updates() As updatesUpdate()
            Get
                Return Me.updatesField
            End Get
            Set(value As updatesUpdate())
                Me.updatesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("keyword", IsNullable:=False)> _
        Public Property keywords() As String()
            Get
                Return Me.keywordsField
            End Get
            Set(value As String())
                Me.keywordsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property classification() As classification
            Get
                Return Me.classificationField
            End Get
            Set(value As classification)
                Me.classificationField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("image", IsNullable:=False)> _
        Public Property images() As imagesImage()
            Get
                Return Me.imagesField
            End Get
            Set(value As imagesImage())
                Me.imagesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("attachment", IsNullable:=False)> _
        Public Property attachments() As attachmentsAttachment()
            Get
                Return Me.attachmentsField
            End Get
            Set(value As attachmentsAttachment())
                Me.attachmentsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("link", IsNullable:=False)> _
        Public Property links() As linksLink()
            Get
                Return Me.linksField
            End Get
            Set(value As linksLink())
                Me.linksField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable:=False)> _
        Public Property results() As result()
            Get
                Return Me.resultsField
            End Get
            Set(value As result())
                Me.resultsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable:=False)> _
        Public Property postprocessed_results() As postprocessed_result()
            Get
                Return Me.postprocessed_resultsField
            End Get
            Set(value As postprocessed_result())
                Me.postprocessed_resultsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property excel_results() As excel_results
            Get
                Return Me.excel_resultsField
            End Get
            Set(value As excel_results)
                Me.excel_resultsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("incident", IsNullable:=False)> _
        Public Property incidents() As incidentsIncident()
            Get
                Return Me.incidentsField
            End Get
            Set(value As incidentsIncident())
                Me.incidentsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("ticket", IsNullable:=False)> _
        Public Property tickets() As ticketsTicket()
            Get
                Return Me.ticketsField
            End Get
            Set(value As ticketsTicket())
                Me.ticketsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property program() As program
            Get
                Return Me.programField
            End Get
            Set(value As program)
                Me.programField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("program", IsNullable:=False)> _
        Public Property target_program() As target_programProgram()
            Get
                Return Me.target_programField
            End Get
            Set(value As target_programProgram())
                Me.target_programField = value
            End Set
        End Property

        '''<remarks/>
        Public Property author() As author
            Get
                Return Me.authorField
            End Get
            Set(value As author)
                Me.authorField = value
            End Set
        End Property

        '''<remarks/>
        Public Property [date]() As [date]
            Get
                Return Me.dateField
            End Get
            Set(value As [date])
                Me.dateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property run_time() As run_time
            Get
                Return Me.run_timeField
            End Get
            Set(value As run_time)
                Me.run_timeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property regtest_internal_use() As regtest_internal_use
            Get
                Return Me.regtest_internal_useField
            End Get
            Set(value As regtest_internal_use)
                Me.regtest_internal_useField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property is_public() As String
            Get
                Return Me.is_publicField
            End Get
            Set(value As String)
                Me.is_publicField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property is_bug() As String
            Get
                Return Me.is_bugField
            End Get
            Set(value As String)
                Me.is_bugField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property status() As status_model
            Get
                Return Me.statusField
            End Get
            Set(value As status_model)
                Me.statusField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property statusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set(value As Boolean)
                Me.statusFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property documentation_status() As status_documentation
            Get
                Return Me.documentation_statusField
            End Get
            Set(value As status_documentation)
                Me.documentation_statusField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property documentation_statusSpecified() As Boolean
            Get
                Return Me.documentation_statusFieldSpecified
            End Get
            Set(value As Boolean)
                Me.documentation_statusFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class path

        Private typeField As absolute_relative

        Private typeFieldSpecified As Boolean

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property type() As absolute_relative
            Get
                Return Me.typeField
            End Get
            Set(value As absolute_relative)
                Me.typeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property typeSpecified() As Boolean
            Get
                Return Me.typeFieldSpecified
            End Get
            Set(value As Boolean)
                Me.typeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum absolute_relative

        '''<remarks/>
        absolute

        '''<remarks/>
        relative
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class range_all

        Private nameField As String

        Private range_operationField As range_operation

        Private range_operationFieldSpecified As Boolean

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property range_operation() As range_operation
            Get
                Return Me.range_operationField
            End Get
            Set(value As range_operation)
                Me.range_operationField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property range_operationSpecified() As Boolean
            Get
                Return Me.range_operationFieldSpecified
            End Get
            Set(value As Boolean)
                Me.range_operationFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum range_operation

        '''<remarks/>
        sum

        '''<remarks/>
        sumabs

        '''<remarks/>
        srss

        '''<remarks/>
        max

        '''<remarks/>
        min

        '''<remarks/>
        avg

        '''<remarks/>
        maxabs

        '''<remarks/>
        minabs

        '''<remarks/>
        avgabs
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class range

        Private nameField As String

        Private value_firstField As String

        Private value_lastField As String

        Private range_operationField As range_operation

        Private range_operationFieldSpecified As Boolean

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property value_first() As String
            Get
                Return Me.value_firstField
            End Get
            Set(value As String)
                Me.value_firstField = value
            End Set
        End Property

        '''<remarks/>
        Public Property value_last() As String
            Get
                Return Me.value_lastField
            End Get
            Set(value As String)
                Me.value_lastField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property range_operation() As range_operation
            Get
                Return Me.range_operationField
            End Get
            Set(value As range_operation)
                Me.range_operationField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property range_operationSpecified() As Boolean
            Get
                Return Me.range_operationFieldSpecified
            End Get
            Set(value As Boolean)
                Me.range_operationFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class postprocessed_result

        Private idField As Decimal

        Private nameField As String

        Private unitsField As result_units

        Private table_nameField As String

        Private rangeField As range

        Private range_allField As range_all

        Private formulaField As formula

        Private updatesField() As result_updatesUpdate

        '''<remarks/>
        Public Property id() As Decimal
            Get
                Return Me.idField
            End Get
            Set(value As Decimal)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property units() As result_units
            Get
                Return Me.unitsField
            End Get
            Set(value As result_units)
                Me.unitsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property table_name() As String
            Get
                Return Me.table_nameField
            End Get
            Set(value As String)
                Me.table_nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property range() As range
            Get
                Return Me.rangeField
            End Get
            Set(value As range)
                Me.rangeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property range_all() As range_all
            Get
                Return Me.range_allField
            End Get
            Set(value As range_all)
                Me.range_allField = value
            End Set
        End Property

        '''<remarks/>
        Public Property formula() As formula
            Get
                Return Me.formulaField
            End Get
            Set(value As formula)
                Me.formulaField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("update", IsNullable:=False)> _
        Public Property updates() As result_updatesUpdate()
            Get
                Return Me.updatesField
            End Get
            Set(value As result_updatesUpdate())
                Me.updatesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class result_units

        Private units_conversionField As yes_no

        Private units_conversionFieldSpecified As Boolean

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property units_conversion() As yes_no
            Get
                Return Me.units_conversionField
            End Get
            Set(value As yes_no)
                Me.units_conversionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property units_conversionSpecified() As Boolean
            Get
                Return Me.units_conversionFieldSpecified
            End Get
            Set(value As Boolean)
                Me.units_conversionFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum yes_no

        '''<remarks/>
        yes

        '''<remarks/>
        no
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class formula

        Private variablesField() As variablesVariable

        Private resultField As result_value

        Private operationField As range_operation

        Private operationFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("variable", IsNullable:=False)> _
        Public Property variables() As variablesVariable()
            Get
                Return Me.variablesField
            End Get
            Set(value As variablesVariable())
                Me.variablesField = value
            End Set
        End Property

        '''<remarks/>
        Public Property result() As result_value
            Get
                Return Me.resultField
            End Get
            Set(value As result_value)
                Me.resultField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property operation() As range_operation
            Get
                Return Me.operationField
            End Get
            Set(value As range_operation)
                Me.operationField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property operationSpecified() As Boolean
            Get
                Return Me.operationFieldSpecified
            End Get
            Set(value As Boolean)
                Me.operationFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class variablesVariable

        Private scale_factorField As Double

        Private lookup_fieldsField As variablesVariableLookup_fields

        Private output_fieldField As variablesVariableOutput_field

        '''<remarks/>
        Public Property scale_factor() As Double
            Get
                Return Me.scale_factorField
            End Get
            Set(value As Double)
                Me.scale_factorField = value
            End Set
        End Property

        '''<remarks/>
        Public Property lookup_fields() As variablesVariableLookup_fields
            Get
                Return Me.lookup_fieldsField
            End Get
            Set(value As variablesVariableLookup_fields)
                Me.lookup_fieldsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property output_field() As variablesVariableOutput_field
            Get
                Return Me.output_fieldField
            End Get
            Set(value As variablesVariableOutput_field)
                Me.output_fieldField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class variablesVariableLookup_fields

        Private rangeField As range

        Private range_allField As range_all

        Private fieldField() As lookup_field

        '''<remarks/>
        Public Property range() As range
            Get
                Return Me.rangeField
            End Get
            Set(value As range)
                Me.rangeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property range_all() As range_all
            Get
                Return Me.range_allField
            End Get
            Set(value As range_all)
                Me.range_allField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("field")> _
        Public Property field() As lookup_field()
            Get
                Return Me.fieldField
            End Get
            Set(value As lookup_field())
                Me.fieldField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class lookup_field

        Private nameField As String

        Private valueField As String

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class variablesVariableOutput_field

        Private nameField As String

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class result_value

        Private benchmarkField As result_valueBenchmark

        Private theoreticalField As result_valueTheoretical

        Private last_bestField As result_valueLast_best

        Private shift_for_calculating_percent_differenceField As Decimal

        Private shift_for_calculating_percent_differenceFieldSpecified As Boolean

        Private zero_toleranceField As Decimal

        Private zero_toleranceFieldSpecified As Boolean

        Private passing_percent_difference_rangeField As Decimal

        Private passing_percent_difference_rangeFieldSpecified As Boolean

        '''<remarks/>
        Public Property benchmark() As result_valueBenchmark
            Get
                Return Me.benchmarkField
            End Get
            Set(value As result_valueBenchmark)
                Me.benchmarkField = value
            End Set
        End Property

        '''<remarks/>
        Public Property theoretical() As result_valueTheoretical
            Get
                Return Me.theoreticalField
            End Get
            Set(value As result_valueTheoretical)
                Me.theoreticalField = value
            End Set
        End Property

        '''<remarks/>
        Public Property last_best() As result_valueLast_best
            Get
                Return Me.last_bestField
            End Get
            Set(value As result_valueLast_best)
                Me.last_bestField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property shift_for_calculating_percent_difference() As Decimal
            Get
                Return Me.shift_for_calculating_percent_differenceField
            End Get
            Set(value As Decimal)
                Me.shift_for_calculating_percent_differenceField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property shift_for_calculating_percent_differenceSpecified() As Boolean
            Get
                Return Me.shift_for_calculating_percent_differenceFieldSpecified
            End Get
            Set(value As Boolean)
                Me.shift_for_calculating_percent_differenceFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property zero_tolerance() As Decimal
            Get
                Return Me.zero_toleranceField
            End Get
            Set(value As Decimal)
                Me.zero_toleranceField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property zero_toleranceSpecified() As Boolean
            Get
                Return Me.zero_toleranceFieldSpecified
            End Get
            Set(value As Boolean)
                Me.zero_toleranceFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property passing_percent_difference_range() As Decimal
            Get
                Return Me.passing_percent_difference_rangeField
            End Get
            Set(value As Decimal)
                Me.passing_percent_difference_rangeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property passing_percent_difference_rangeSpecified() As Boolean
            Get
                Return Me.passing_percent_difference_rangeFieldSpecified
            End Get
            Set(value As Boolean)
                Me.passing_percent_difference_rangeFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class result_valueBenchmark

        Private is_correctField As String

        Private significant_digitsField As String

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property is_correct() As String
            Get
                Return Me.is_correctField
            End Get
            Set(value As String)
                Me.is_correctField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property significant_digits() As String
            Get
                Return Me.significant_digitsField
            End Get
            Set(value As String)
                Me.significant_digitsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class result_valueTheoretical

        Private significant_digitsField As String

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property significant_digits() As String
            Get
                Return Me.significant_digitsField
            End Get
            Set(value As String)
                Me.significant_digitsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class result_valueLast_best

        Private significant_digitsField As String

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property significant_digits() As String
            Get
                Return Me.significant_digitsField
            End Get
            Set(value As String)
                Me.significant_digitsField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class result_updatesUpdate

        Private idField As String

        Private commentField As String

        '''<remarks/>
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        Public Property comment() As String
            Get
                Return Me.commentField
            End Get
            Set(value As String)
                Me.commentField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class updatesUpdate

        Private idField As String

        Private dateField As [date]

        Private personField As String

        Private ticketField As String

        Private buildField As String

        Private commentField As String

        '''<remarks/>
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        Public Property [date]() As [date]
            Get
                Return Me.dateField
            End Get
            Set(value As [date])
                Me.dateField = value
            End Set
        End Property

        '''<remarks/>
        Public Property person() As String
            Get
                Return Me.personField
            End Get
            Set(value As String)
                Me.personField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ticket() As String
            Get
                Return Me.ticketField
            End Get
            Set(value As String)
                Me.ticketField = value
            End Set
        End Property

        '''<remarks/>
        Public Property build() As String
            Get
                Return Me.buildField
            End Get
            Set(value As String)
                Me.buildField = value
            End Set
        End Property

        '''<remarks/>
        Public Property comment() As String
            Get
                Return Me.commentField
            End Get
            Set(value As String)
                Me.commentField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class [date]

        Private dayField As String

        Private monthField As String

        Private yearField As String

        '''<remarks/>
        Public Property day() As String
            Get
                Return Me.dayField
            End Get
            Set(value As String)
                Me.dayField = value
            End Set
        End Property

        '''<remarks/>
        Public Property month() As String
            Get
                Return Me.monthField
            End Get
            Set(value As String)
                Me.monthField = value
            End Set
        End Property

        '''<remarks/>
        Public Property year() As String
            Get
                Return Me.yearField
            End Get
            Set(value As String)
                Me.yearField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class classification

        Private valueField As classificationValue

        '''<remarks/>
        Public Property value() As classificationValue
            Get
                Return Me.valueField
            End Get
            Set(value As classificationValue)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class classificationValue

        Private level_1Field As classifications_level1

        Private level_2Field As String

        '''<remarks/>
        Public Property level_1() As classifications_level1
            Get
                Return Me.level_1Field
            End Get
            Set(value As classifications_level1)
                Me.level_1Field = value
            End Set
        End Property

        '''<remarks/>
        Public Property level_2() As String
            Get
                Return Me.level_2Field
            End Get
            Set(value As String)
                Me.level_2Field = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum classifications_level1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Regression Example")> _
        RegressionExample

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Published Verification Example")> _
        PublishedVerificationExample

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Internal Verification Example")> _
        InternalVerificationExample

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("")> _
        Item
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class imagesImage

        Private titleField As String

        Private pathField As String

        '''<remarks/>
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set(value As String)
                Me.titleField = value
            End Set
        End Property

        '''<remarks/>
        Public Property path() As String
            Get
                Return Me.pathField
            End Get
            Set(value As String)
                Me.pathField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class attachmentsAttachment

        Private titleField As String

        Private pathField As String

        '''<remarks/>
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set(value As String)
                Me.titleField = value
            End Set
        End Property

        '''<remarks/>
        Public Property path() As String
            Get
                Return Me.pathField
            End Get
            Set(value As String)
                Me.pathField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class linksLink

        Private titleField As String

        Private urlField As String

        '''<remarks/>
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set(value As String)
                Me.titleField = value
            End Set
        End Property

        '''<remarks/>
        Public Property url() As String
            Get
                Return Me.urlField
            End Get
            Set(value As String)
                Me.urlField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class result

        Private idField As Decimal

        Private nameField As String

        Private unitsField As result_units

        Private table_nameField As String

        Private lookup_fieldsField() As lookup_field

        Private output_fieldField As output_field

        Private updatesField() As result_updatesUpdate

        '''<remarks/>
        Public Property id() As Decimal
            Get
                Return Me.idField
            End Get
            Set(value As Decimal)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property units() As result_units
            Get
                Return Me.unitsField
            End Get
            Set(value As result_units)
                Me.unitsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property table_name() As String
            Get
                Return Me.table_nameField
            End Get
            Set(value As String)
                Me.table_nameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable:=False)> _
        Public Property lookup_fields() As lookup_field()
            Get
                Return Me.lookup_fieldsField
            End Get
            Set(value As lookup_field())
                Me.lookup_fieldsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property output_field() As output_field
            Get
                Return Me.output_fieldField
            End Get
            Set(value As output_field)
                Me.output_fieldField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("update", IsNullable:=False)> _
        Public Property updates() As result_updatesUpdate()
            Get
                Return Me.updatesField
            End Get
            Set(value As result_updatesUpdate())
                Me.updatesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class output_field

        Private nameField As String

        Private valueField As result_value

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property value() As result_value
            Get
                Return Me.valueField
            End Get
            Set(value As result_value)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class excel_results

        Private excel_fileField As excel_file

        '''<remarks/>
        Public Property excel_file() As excel_file
            Get
                Return Me.excel_fileField
            End Get
            Set(value As excel_file)
                Me.excel_fileField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class excel_file

        Private pathField As String

        '''<remarks/>
        Public Property path() As String
            Get
                Return Me.pathField
            End Get
            Set(value As String)
                Me.pathField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class incidentsIncident

        Private numberField As String

        '''<remarks/>
        Public Property number() As String
            Get
                Return Me.numberField
            End Get
            Set(value As String)
                Me.numberField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class ticketsTicket

        Private numberField As String

        '''<remarks/>
        Public Property number() As String
            Get
                Return Me.numberField
            End Get
            Set(value As String)
                Me.numberField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class program

        Private nameField As program_name

        Private versionField As String

        Private version_for_last_best_valueField As String

        '''<remarks/>
        Public Property name() As program_name
            Get
                Return Me.nameField
            End Get
            Set(value As program_name)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set(value As String)
                Me.versionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property version_for_last_best_value() As String
            Get
                Return Me.version_for_last_best_valueField
            End Get
            Set(value As String)
                Me.version_for_last_best_valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum program_name

        '''<remarks/>
        SAP2000

        '''<remarks/>
        CSiBridge

        '''<remarks/>
        ETABS

        '''<remarks/>
        SAFE

        '''<remarks/>
        Perform3D
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class target_programProgram

        Private nameField As program_name

        '''<remarks/>
        Public Property name() As program_name
            Get
                Return Me.nameField
            End Get
            Set(value As program_name)
                Me.nameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class author

        Private nameField As String

        Private companyField As String

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property company() As String
            Get
                Return Me.companyField
            End Get
            Set(value As String)
                Me.companyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class run_time

        Private minutesField As Decimal

        '''<remarks/>
        Public Property minutes() As Decimal
            Get
                Return Me.minutesField
            End Get
            Set(value As Decimal)
                Me.minutesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class regtest_internal_use

        Private excel_resultsField() As regtest_internal_useResult

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable:=False)> _
        Public Property excel_results() As regtest_internal_useResult()
            Get
                Return Me.excel_resultsField
            End Get
            Set(value As regtest_internal_useResult())
                Me.excel_resultsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
    Partial Public Class regtest_internal_useResult

        Private idField As Decimal

        Private nameField As String

        Private unitsField As result_units

        Private valueField As result_value

        Private updatesField() As result_updatesUpdate

        '''<remarks/>
        Public Property id() As Decimal
            Get
                Return Me.idField
            End Get
            Set(value As Decimal)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property units() As result_units
            Get
                Return Me.unitsField
            End Get
            Set(value As result_units)
                Me.unitsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property value() As result_value
            Get
                Return Me.valueField
            End Get
            Set(value As result_value)
                Me.valueField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("update", IsNullable:=False)> _
        Public Property updates() As result_updatesUpdate()
            Get
                Return Me.updatesField
            End Get
            Set(value As result_updatesUpdate())
                Me.updatesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum status_model

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("to do")> _
        todo

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("complete XML file")> _
        completeXMLfile

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("add benchmark values")> _
        addbenchmarkvalues

        '''<remarks/>
        finalize

        '''<remarks/>
        done

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("add benchmark values after bug fixed")> _
        addbenchmarkvaluesafterbugfixed

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("add benchmark values after output tabulated")> _
        addbenchmarkvaluesafteroutputtabulated

        '''<remarks/>
        initial
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum status_documentation

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("not applicable")> _
        notapplicable

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("to do")> _
        todo

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("in progress")> _
        inprogress

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("benchmark needs updating")> _
        benchmarkneedsupdating

        '''<remarks/>
        done

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("")> _
        Item
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class tests

        Private testField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("test")> _
        Public Property test() As String()
            Get
                Return Me.testField
            End Get
            Set(value As String())
                Me.testField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class updates

        Private updateField() As updatesUpdate

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("update")> _
        Public Property update() As updatesUpdate()
            Get
                Return Me.updateField
            End Get
            Set(value As updatesUpdate())
                Me.updateField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class keywords

        Private keywordField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("keyword")> _
        Public Property keyword() As String()
            Get
                Return Me.keywordField
            End Get
            Set(value As String())
                Me.keywordField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class images

        Private imageField() As imagesImage

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("image")> _
        Public Property image() As imagesImage()
            Get
                Return Me.imageField
            End Get
            Set(value As imagesImage())
                Me.imageField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class attachments

        Private attachmentField() As attachmentsAttachment

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("attachment")> _
        Public Property attachment() As attachmentsAttachment()
            Get
                Return Me.attachmentField
            End Get
            Set(value As attachmentsAttachment())
                Me.attachmentField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class links

        Private linkField() As linksLink

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("link")> _
        Public Property link() As linksLink()
            Get
                Return Me.linkField
            End Get
            Set(value As linksLink())
                Me.linkField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class results

        Private resultField() As result

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("result")> _
        Public Property result() As result()
            Get
                Return Me.resultField
            End Get
            Set(value As result())
                Me.resultField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class lookup_fields

        Private fieldField() As lookup_field

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("field")> _
        Public Property field() As lookup_field()
            Get
                Return Me.fieldField
            End Get
            Set(value As lookup_field())
                Me.fieldField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class postprocessed_results

        Private resultField() As postprocessed_result

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("result")> _
        Public Property result() As postprocessed_result()
            Get
                Return Me.resultField
            End Get
            Set(value As postprocessed_result())
                Me.resultField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class variables

        Private variableField() As variablesVariable

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("variable")> _
        Public Property variable() As variablesVariable()
            Get
                Return Me.variableField
            End Get
            Set(value As variablesVariable())
                Me.variableField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute("excel_result", [Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class excel_result1

        Private idField As Decimal

        Private idFieldSpecified As Boolean

        Private nameField As String

        '''<remarks/>
        Public Property id() As Decimal
            Get
                Return Me.idField
            End Get
            Set(value As Decimal)
                Me.idField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property idSpecified() As Boolean
            Get
                Return Me.idFieldSpecified
            End Get
            Set(value As Boolean)
                Me.idFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class incidents

        Private incidentField() As incidentsIncident

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("incident")> _
        Public Property incident() As incidentsIncident()
            Get
                Return Me.incidentField
            End Get
            Set(value As incidentsIncident())
                Me.incidentField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class tickets

        Private ticketField() As ticketsTicket

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ticket")> _
        Public Property ticket() As ticketsTicket()
            Get
                Return Me.ticketField
            End Get
            Set(value As ticketsTicket())
                Me.ticketField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class target_program

        Private programField() As target_programProgram

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("program")> _
        Public Property program() As target_programProgram()
            Get
                Return Me.programField
            End Get
            Set(value As target_programProgram())
                Me.programField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
    Partial Public Class bridge_objects

        Private bridge_objectField() As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("bridge_object")> _
        Public Property bridge_object() As String()
            Get
                Return Me.bridge_objectField
            End Get
            Set(value As String())
                Me.bridge_objectField = value
            End Set
        End Property
    End Class
End Namespace
