'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.17929.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com"), _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiberkeley.com", IsNullable:=False)> _
Partial Public Class tabularOutput

    Private filenameField As String

    Private v9unitsField As Boolean

    Private tableSetField As tabularOutputTableSet

    Private saveField As Boolean

    Private saveFieldSpecified As Boolean

    Public Sub New()
        MyBase.New()
        Me.v9unitsField = False
    End Sub

    '''<remarks/>
    Public Property filename() As String
        Get
            Return Me.filenameField
        End Get
        Set(value As String)
            Me.filenameField = value
        End Set
    End Property

    '''<remarks/>
    Public Property v9units() As Boolean
        Get
            Return Me.v9unitsField
        End Get
        Set(value As Boolean)
            Me.v9unitsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property tableSet() As tabularOutputTableSet
        Get
            Return Me.tableSetField
        End Get
        Set(value As tabularOutputTableSet)
            Me.tableSetField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property save() As Boolean
        Get
            Return Me.saveField
        End Get
        Set(value As Boolean)
            Me.saveField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()> _
    Public Property saveSpecified() As Boolean
        Get
            Return Me.saveFieldSpecified
        End Get
        Set(value As Boolean)
            Me.saveFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Partial Public Class tabularOutputTableSet

    Private optionsField As tabularOutputTableSetOptions

    Private tablesField() As tabularOutputTableSetTable

    Private nameField As String

    '''<remarks/>
    Public Property options() As tabularOutputTableSetOptions
        Get
            Return Me.optionsField
        End Get
        Set(value As tabularOutputTableSetOptions)
            Me.optionsField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("table", IsNullable:=False)> _
    Public Property tables() As tabularOutputTableSetTable()
        Get
            Return Me.tablesField
        End Get
        Set(value As tabularOutputTableSetTable())
            Me.tablesField = value
        End Set
    End Property

    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()> _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set(value As String)
            Me.nameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Partial Public Class tabularOutputTableSetOptions

    Private showSelectionOnlyField As Boolean

    Private showOnlyIfUsedInModelField As Boolean

    Private showAllFieldsField As Boolean

    Private unitsField As tabularOutputTableSetOptionsUnits

    Private groupsField As tabularOutputTableSetOptionsGroups

    Private loadPatternsField As tabularOutputTableSetOptionsLoadPatterns

    Private loadCasesField As tabularOutputTableSetOptionsLoadCases

    Private loadCombinationsField As tabularOutputTableSetOptionsLoadCombinations

    Private multiStepField As tabularOutputTableSetOptionsMultiStep

    Private combineCaseStepFieldsField As Boolean

    Public Sub New()
        MyBase.New()
        Me.showSelectionOnlyField = True
        Me.showOnlyIfUsedInModelField = True
        Me.showAllFieldsField = False
        Me.combineCaseStepFieldsField = False
    End Sub

    '''<remarks/>
    Public Property showSelectionOnly() As Boolean
        Get
            Return Me.showSelectionOnlyField
        End Get
        Set(value As Boolean)
            Me.showSelectionOnlyField = value
        End Set
    End Property

    '''<remarks/>
    Public Property showOnlyIfUsedInModel() As Boolean
        Get
            Return Me.showOnlyIfUsedInModelField
        End Get
        Set(value As Boolean)
            Me.showOnlyIfUsedInModelField = value
        End Set
    End Property

    '''<remarks/>
    Public Property showAllFields() As Boolean
        Get
            Return Me.showAllFieldsField
        End Get
        Set(value As Boolean)
            Me.showAllFieldsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property units() As tabularOutputTableSetOptionsUnits
        Get
            Return Me.unitsField
        End Get
        Set(value As tabularOutputTableSetOptionsUnits)
            Me.unitsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property groups() As tabularOutputTableSetOptionsGroups
        Get
            Return Me.groupsField
        End Get
        Set(value As tabularOutputTableSetOptionsGroups)
            Me.groupsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property loadPatterns() As tabularOutputTableSetOptionsLoadPatterns
        Get
            Return Me.loadPatternsField
        End Get
        Set(value As tabularOutputTableSetOptionsLoadPatterns)
            Me.loadPatternsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property loadCases() As tabularOutputTableSetOptionsLoadCases
        Get
            Return Me.loadCasesField
        End Get
        Set(value As tabularOutputTableSetOptionsLoadCases)
            Me.loadCasesField = value
        End Set
    End Property

    '''<remarks/>
    Public Property loadCombinations() As tabularOutputTableSetOptionsLoadCombinations
        Get
            Return Me.loadCombinationsField
        End Get
        Set(value As tabularOutputTableSetOptionsLoadCombinations)
            Me.loadCombinationsField = value
        End Set
    End Property

    '''<remarks/>
    Public Property multiStep() As tabularOutputTableSetOptionsMultiStep
        Get
            Return Me.multiStepField
        End Get
        Set(value As tabularOutputTableSetOptionsMultiStep)
            Me.multiStepField = value
        End Set
    End Property

    '''<remarks/>
    Public Property combineCaseStepFields() As Boolean
        Get
            Return Me.combineCaseStepFieldsField
        End Get
        Set(value As Boolean)
            Me.combineCaseStepFieldsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Partial Public Class tabularOutputTableSetOptionsUnits

    Private forceUnitField As tabularOutputTableSetOptionsUnitsForceUnit

    Private lengthUnitField As tabularOutputTableSetOptionsUnitsLengthUnit

    Private temperatureUnitField As tabularOutputTableSetOptionsUnitsTemperatureUnit

    Public Sub New()
        MyBase.New()
        Me.forceUnitField = tabularOutputTableSetOptionsUnitsForceUnit.Item
        Me.lengthUnitField = tabularOutputTableSetOptionsUnitsLengthUnit.Item
        Me.temperatureUnitField = tabularOutputTableSetOptionsUnitsTemperatureUnit.Item
    End Sub

    '''<remarks/>
    Public Property forceUnit() As tabularOutputTableSetOptionsUnitsForceUnit
        Get
            Return Me.forceUnitField
        End Get
        Set(value As tabularOutputTableSetOptionsUnitsForceUnit)
            Me.forceUnitField = value
        End Set
    End Property

    '''<remarks/>
    Public Property lengthUnit() As tabularOutputTableSetOptionsUnitsLengthUnit
        Get
            Return Me.lengthUnitField
        End Get
        Set(value As tabularOutputTableSetOptionsUnitsLengthUnit)
            Me.lengthUnitField = value
        End Set
    End Property

    '''<remarks/>
    Public Property temperatureUnit() As tabularOutputTableSetOptionsUnitsTemperatureUnit
        Get
            Return Me.temperatureUnitField
        End Get
        Set(value As tabularOutputTableSetOptionsUnitsTemperatureUnit)
            Me.temperatureUnitField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Public Enum tabularOutputTableSetOptionsUnitsForceUnit

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("")> _
    Item

    '''<remarks/>
    lb

    '''<remarks/>
    kip

    '''<remarks/>
    N

    '''<remarks/>
    kN

    '''<remarks/>
    kgf

    '''<remarks/>
    tonf
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Public Enum tabularOutputTableSetOptionsUnitsLengthUnit

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("")> _
    Item

    '''<remarks/>
    [in]

    '''<remarks/>
    ft

    '''<remarks/>
    micron

    '''<remarks/>
    mm

    '''<remarks/>
    cm

    '''<remarks/>
    m
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Public Enum tabularOutputTableSetOptionsUnitsTemperatureUnit

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("")> _
    Item

    '''<remarks/>
    F

    '''<remarks/>
    C
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Partial Public Class tabularOutputTableSetOptionsGroups

    Private groupField As String

    '''<remarks/>
    Public Property group() As String
        Get
            Return Me.groupField
        End Get
        Set(value As String)
            Me.groupField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Partial Public Class tabularOutputTableSetOptionsLoadPatterns

    Private loadPatternField As String

    '''<remarks/>
    Public Property loadPattern() As String
        Get
            Return Me.loadPatternField
        End Get
        Set(value As String)
            Me.loadPatternField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Partial Public Class tabularOutputTableSetOptionsLoadCases

    Private loadCaseField As String

    '''<remarks/>
    Public Property loadCase() As String
        Get
            Return Me.loadCaseField
        End Get
        Set(value As String)
            Me.loadCaseField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Diagnostics.DebuggerStepThroughAttribute(), _
 System.ComponentModel.DesignerCategoryAttribute("code"), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Partial Public Class tabularOutputTableSetOptionsLoadCombinations

    Private loadCombinationField As String

    '''<remarks/>
    Public Property loadCombination() As String
        Get
            Return Me.loadCombinationField
        End Get
        Set(value As String)
            Me.loadCombinationField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Public Enum tabularOutputTableSetOptionsMultiStep

    '''<remarks/>
    Envelopes

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Step-by-Step")> _
    StepbyStep

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Last Step")> _
    LastStep
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
 System.SerializableAttribute(), _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiberkeley.com")> _
Public Enum tabularOutputTableSetTable

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Program Control")> _
    ProgramControl

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Project Information")> _
    ProjectInformation

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("General Structure Information")> _
    GeneralStructureInformation

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Story Data")> _
    StoryData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Grid Systems")> _
    GridSystems

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Grid Lines")> _
    GridLines

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Coordinates Data")> _
    JointCoordinatesData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Coordinates")> _
    JointCoordinates

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Column Connectivity Data")> _
    ColumnConnectivityData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Column Connectivity")> _
    ColumnConnectivity

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Beam Connectivity Data")> _
    BeamConnectivityData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Beam Connectivity")> _
    BeamConnectivity

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Brace Connectivity Data")> _
    BraceConnectivityData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Brace Connectivity")> _
    BraceConnectivity

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Null Frame Connectivity Data")> _
    NullFrameConnectivityData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Null Frame Connectivity")> _
    NullFrameConnectivity

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Floor Connectivity Data")> _
    FloorConnectivityData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Floor Connectivity")> _
    FloorConnectivity

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Wall Connectivity Data")> _
    WallConnectivityData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Wall Connectivity")> _
    WallConnectivity

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Null Shell Connectivity Data")> _
    NullShellConnectivityData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Null Shell Connectivity")> _
    NullShellConnectivity

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Connectivity")> _
    LinkConnectivity

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Objects and Elements - Joints")> _
    ObjectsandElementsJoints

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Objects and Elements - Frames")> _
    ObjectsandElementsFrames

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Objects and Elements - Shells")> _
    ObjectsandElementsShells

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Objects and Elements - Links")> _
    ObjectsandElementsLinks

    '''<remarks/>
    Diaphragms

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material Properties - Summary")> _
    MaterialPropertiesSummary

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material Properties - Steel")> _
    MaterialPropertiesSteel

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material Properties - Concrete")> _
    MaterialPropertiesConcrete

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material Properties - Masonry")> _
    MaterialPropertiesMasonry

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material Properties - Rebar")> _
    MaterialPropertiesRebar

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material Properties - Tendon")> _
    MaterialPropertiesTendon

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material Properties - Aluminum")> _
    MaterialPropertiesAluminum

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material Properties - Cold Formed")> _
    MaterialPropertiesColdFormed

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material Properties - Other")> _
    MaterialPropertiesOther

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Sections - Summary")> _
    FrameSectionsSummary

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Sections")> _
    FrameSections

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Rebar Data")> _
    ConcreteColumnRebarData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Rebar Data")> _
    ConcreteBeamRebarData

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Sections - Summary")> _
    ShellSectionsSummary

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Sections - Slab")> _
    ShellSectionsSlab

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Sections - Deck")> _
    ShellSectionsDeck

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Sections - Wall")> _
    ShellSectionsWall

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Pier Section Properties")> _
    PierSectionProperties

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Spandrel Section Properties")> _
    SpandrelSectionProperties

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Reinforcing Bar Sizes")> _
    ReinforcingBarSizes

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Properties - Summary")> _
    LinkPropertiesSummary

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Properties - Linear")> _
    LinkPropertiesLinear

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Properties - Damper")> _
    LinkPropertiesDamper

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Properties - Gap")> _
    LinkPropertiesGap

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Properties - Hook")> _
    LinkPropertiesHook

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Properties - Plastic (Wen)")> _
    LinkPropertiesPlasticWen

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Properties - Rubber Isolator")> _
    LinkPropertiesRubberIsolator

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Properties - Friction Isolator")> _
    LinkPropertiesFrictionIsolator

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Spring Properties - Point")> _
    SpringPropertiesPoint

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Spring Properties - Line")> _
    SpringPropertiesLine

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Spring Properties - Area")> _
    SpringPropertiesArea

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Mass Source")> _
    MassSource

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Group Definitions")> _
    GroupDefinitions

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Group Assignments")> _
    GroupAssignments

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Section Cuts")> _
    SectionCuts

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Section Cuts - Quads")> _
    SectionCutsQuads

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Generalized Displacement - Translational")> _
    GeneralizedDisplacementTranslational

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Generalized Displacement - Rotational")> _
    GeneralizedDisplacementRotational

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Patterns")> _
    LoadPatterns

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Uniform Load Sets")> _
    ShellUniformLoadSets

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - ASCE 7-02")> _
    AutoWindASCE702

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - ASCE 7-05")> _
    AutoWindASCE705

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - ASCE 7-10")> _
    AutoWindASCE710

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - ASCE 7-88")> _
    AutoWindASCE788

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - ASCE 7-95")> _
    AutoWindASCE795

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - AS/NZS 1170.2:2002")> _
    AutoWindASNZS117022002

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - AS/NZS 1170.2:2011")> _
    AutoWindASNZS117022011

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - BOCA 96")> _
    AutoWindBOCA96

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - BS 6399-95")> _
    AutoWindBS639995

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - Chinese 2010")> _
    AutoWindChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - Eurocode 1-2005")> _
    AutoWindEurocode12005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - IS 875-1987")> _
    AutoWindIS8751987

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - Mexican")> _
    AutoWindMexican

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - NBCC 2005")> _
    AutoWindNBCC2005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - NBCC 2010")> _
    AutoWindNBCC2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - NBCC 95")> _
    AutoWindNBCC95

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - NTC 2008")> _
    AutoWindNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - TS 498-97")> _
    AutoWindTS49897

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - UBC 94")> _
    AutoWindUBC94

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - UBC 97")> _
    AutoWindUBC97

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind - User Loads")> _
    AutoWindUserLoads

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind Loads to Stories")> _
    AutoWindLoadstoStories

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Wind Loads to Diaphragms")> _
    AutoWindLoadstoDiaphragms

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - AS 1170:2007")> _
    AutoSeismicAS11702007

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - ASCE 7-02")> _
    AutoSeismicASCE702

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - ASCE 7-05")> _
    AutoSeismicASCE705

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - ASCE 7-10")> _
    AutoSeismicASCE710

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - BOCA 96")> _
    AutoSeismicBOCA96

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - Chinese 2010")> _
    AutoSeismicChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - TSC-2007")> _
    AutoSeismicTSC2007

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - Eurocode 8-2004")> _
    AutoSeismicEurocode82004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - IS 1893:2002")> _
    AutoSeismicIS18932002

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - NBCC 2005")> _
    AutoSeismicNBCC2005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - NBCC 2010")> _
    AutoSeismicNBCC2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - NBCC 95")> _
    AutoSeismicNBCC95

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - NEHRP 97")> _
    AutoSeismicNEHRP97

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - NTC 2008")> _
    AutoSeismicNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - NZS 1170:2004")> _
    AutoSeismicNZS11702004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - UBC 94")> _
    AutoSeismicUBC94

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - UBC 97")> _
    AutoSeismicUBC97

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - UBC 97 Isolated")> _
    AutoSeismicUBC97Isolated

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - User Coefficients")> _
    AutoSeismicUserCoefficients

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic - User Loads")> _
    AutoSeismicUserLoads

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic Loads to Stories")> _
    AutoSeismicLoadstoStories

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Auto Seismic Loads to Diaphragms")> _
    AutoSeismicLoadstoDiaphragms

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Loads - Force")> _
    JointLoadsForce

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Loads - Displacement")> _
    JointLoadsDisplacement

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Loads - Temperature")> _
    JointLoadsTemperature

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Loads - Point")> _
    FrameLoadsPoint

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Loads - Distributed")> _
    FrameLoadsDistributed

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Loads - Temperature")> _
    FrameLoadsTemperature

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Loads - Uniform")> _
    ShellLoadsUniform

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Loads - Uniform Load Sets")> _
    ShellLoadsUniformLoadSets

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Loads - Temperature")> _
    ShellLoadsTemperature

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Assignments - Summary")> _
    JointAssignmentsSummary

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Assignments - Restraints")> _
    JointAssignmentsRestraints

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Assignments - Springs")> _
    JointAssignmentsSprings

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Assignments - Diaphragms")> _
    JointAssignmentsDiaphragms

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Assignments - Panel Zones")> _
    JointAssignmentsPanelZones

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Assignments - Mass")> _
    JointAssignmentsMass

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Assignments - Mesh Options")> _
    JointAssignmentsMeshOptions

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Summary")> _
    FrameAssignmentsSummary

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Sections")> _
    FrameAssignmentsSections

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Property Modifiers")> _
    FrameAssignmentsPropertyModifiers

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Releases")> _
    FrameAssignmentsReleases

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Offsets")> _
    FrameAssignmentsOffsets

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Insertion Points")> _
    FrameAssignmentsInsertionPoints

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Local Axes")> _
    FrameAssignmentsLocalAxes

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Nonprismatic Parameters")> _
    FrameAssignmentsNonprismaticParameters

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Output Stations")> _
    FrameAssignmentsOutputStations

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - T/C Limits")> _
    FrameAssignmentsTCLimits

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Springs")> _
    FrameAssignmentsSprings

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Mass")> _
    FrameAssignmentsMass

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Pier/Spandrel")> _
    FrameAssignmentsPierSpandrel

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Mesh Options")> _
    FrameAssignmentsMeshOptions

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Moment Frame Beam Type")> _
    FrameAssignmentsMomentFrameBeamType

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Hinge Summary")> _
    FrameAssignmentsHingeSummary

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Hinge - ASCE 41-13 Concrete Column")> _
    FrameAssignmentsHingeASCE4113ConcreteColumn

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Hinge - ASCE 41-13 Concrete Beam")> _
    FrameAssignmentsHingeASCE4113ConcreteBeam

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Hinge - ASCE 41-13 Steel Column")> _
    FrameAssignmentsHingeASCE4113SteelColumn

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Hinge - ASCE 41-13 Steel Beam")> _
    FrameAssignmentsHingeASCE4113SteelBeam

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Hinge - ASCE 41-13 Steel Brace")> _
    FrameAssignmentsHingeASCE4113SteelBrace

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Assignments - Hinge - Caltrans Flexural")> _
    FrameAssignmentsHingeCaltransFlexural

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Assignments - Summary")> _
    ShellAssignmentsSummary

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Assignments - Sections")> _
    ShellAssignmentsSections

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Assignments - Property Modifiers")> _
    ShellAssignmentsPropertyModifiers

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Assignments - Diaphragms")> _
    ShellAssignmentsDiaphragms

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Assignments - Local Axes")> _
    ShellAssignmentsLocalAxes

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Assignments - Springs")> _
    ShellAssignmentsSprings

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Assignments - Mass")> _
    ShellAssignmentsMass

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Assignments - Wall Hinges")> _
    ShellAssignmentsWallHinges

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Assignments - Pier/Spandrel")> _
    ShellAssignmentsPierSpandrel

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Assignments - Floor Mesh Options")> _
    ShellAssignmentsFloorMeshOptions

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Assignments - Summary")> _
    LinkAssignmentsSummary

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Assignments - Properties")> _
    LinkAssignmentsProperties

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Assignments - Local Axes")> _
    LinkAssignmentsLocalAxes

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material List by Element Type")> _
    MaterialListbyElementType

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material List by Section")> _
    MaterialListbySection

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Material List by Story")> _
    MaterialListbyStory

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Mass Summary by Story")> _
    MassSummarybyStory

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Mass Summary by Diaphragm")> _
    MassSummarybyDiaphragm

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Mass Summary by Group")> _
    MassSummarybyGroup

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Assembled Joint Masses")> _
    AssembledJointMasses

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Active Degrees of Freedom")> _
    ActiveDegreesofFreedom

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("P-delta Options")> _
    PdeltaOptions

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Mass Source")> _
    MassSource1

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("SAPFire Options")> _
    SAPFireOptions

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - From File")> _
    ResponseSpectrumFunctionFromFile

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - AS 1170:2007")> _
    ResponseSpectrumFunctionAS11702007

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - ASCE 7-02")> _
    ResponseSpectrumFunctionASCE702

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - ASCE 7-05")> _
    ResponseSpectrumFunctionASCE705

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - ASCE 7-10")> _
    ResponseSpectrumFunctionASCE710

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - BOCA 96")> _
    ResponseSpectrumFunctionBOCA96

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - GB50011-2010")> _
    ResponseSpectrumFunctionGB500112010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - TSC-2007")> _
    ResponseSpectrumFunctionTSC2007

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - Eurocode 8-1994")> _
    ResponseSpectrumFunctionEurocode81994

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - Eurocode 8-2004")> _
    ResponseSpectrumFunctionEurocode82004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - IS 1893:2002")> _
    ResponseSpectrumFunctionIS18932002

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - Italian 3274")> _
    ResponseSpectrumFunctionItalian3274

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - NBCC 2005")> _
    ResponseSpectrumFunctionNBCC2005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - NBCC 2010")> _
    ResponseSpectrumFunctionNBCC2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - NBCC 95")> _
    ResponseSpectrumFunctionNBCC95

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - NEHRP 97")> _
    ResponseSpectrumFunctionNEHRP97

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - NTC 2008")> _
    ResponseSpectrumFunctionNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - NZS 1170:2004")> _
    ResponseSpectrumFunctionNZS11702004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - NZS 4203")> _
    ResponseSpectrumFunctionNZS4203

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - UBC 94")> _
    ResponseSpectrumFunctionUBC94

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - UBC 97")> _
    ResponseSpectrumFunctionUBC97

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Function - User")> _
    ResponseSpectrumFunctionUser

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Time History Function - From File")> _
    TimeHistoryFunctionFromFile

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Time History Function - Sine")> _
    TimeHistoryFunctionSine

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Time History Function - Cosine")> _
    TimeHistoryFunctionCosine

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Time History Function - Ramp")> _
    TimeHistoryFunctionRamp

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Time History Function - Sawtooth")> _
    TimeHistoryFunctionSawtooth

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Time History Function - Triangular")> _
    TimeHistoryFunctionTriangular

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Time History Function - User")> _
    TimeHistoryFunctionUser

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Time History Function - User Periodic")> _
    TimeHistoryFunctionUserPeriodic

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Summary")> _
    LoadCasesSummary

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Static - Linear")> _
    LoadCasesStaticLinear

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Static - Nonlinear")> _
    LoadCasesStaticNonlinear

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Modal - Eigen")> _
    LoadCasesModalEigen

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Modal - Ritz")> _
    LoadCasesModalRitz

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Response Spectrum")> _
    LoadCasesResponseSpectrum

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Response Spectrum Eccentricity Override")> _
    LoadCasesResponseSpectrumEccentricityOverride

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Staged Construction")> _
    LoadCasesStagedConstruction

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Time History - Linear Modal")> _
    LoadCasesTimeHistoryLinearModal

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Time History - Linear Direct Integration")> _
    LoadCasesTimeHistoryLinearDirectIntegration

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Time History - Nonlinear Modal")> _
    LoadCasesTimeHistoryNonlinearModal

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Time History - Nonlinear Direct Integration")> _
    LoadCasesTimeHistoryNonlinearDirectIntegration

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Buckling")> _
    LoadCasesBuckling

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Proportional Damping")> _
    LoadCasesProportionalDamping

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Interpolated Damping")> _
    LoadCasesInterpolatedDamping

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Cases - Damping Overrides")> _
    LoadCasesDampingOverrides

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Load Combinations")> _
    LoadCombinations

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Displacements")> _
    JointDisplacements

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Displacements - Absolute")> _
    JointDisplacementsAbsolute

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Displacements - Generalized")> _
    JointDisplacementsGeneralized

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Velocities - Relative")> _
    JointVelocitiesRelative

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Velocities - Absolute")> _
    JointVelocitiesAbsolute

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Accelerations - Relative")> _
    JointAccelerationsRelative

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Accelerations - Absolute")> _
    JointAccelerationsAbsolute

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Drifts")> _
    JointDrifts

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Diaphragm Center of Mass Displacements")> _
    DiaphragmCenterofMassDisplacements

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Diaphragm Drifts")> _
    DiaphragmDrifts

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Diaphragm Accelerations")> _
    DiaphragmAccelerations

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Story Max/Avg Displacements")> _
    StoryMaxAvgDisplacements

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Story Drifts")> _
    StoryDrifts

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Story Accelerations")> _
    StoryAccelerations

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Base Reactions")> _
    BaseReactions

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Joint Reactions")> _
    JointReactions

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Design Reactions")> _
    DesignReactions

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Modal Periods and Frequencies")> _
    ModalPeriodsandFrequencies

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Modal Participating Mass Ratios")> _
    ModalParticipatingMassRatios

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Modal Load Participation Ratios")> _
    ModalLoadParticipationRatios

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Modal Participation Factors")> _
    ModalParticipationFactors

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Modal Direction Factors")> _
    ModalDirectionFactors

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Response Spectrum Modal Information")> _
    ResponseSpectrumModalInformation

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Buckling Factors")> _
    BucklingFactors

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Centers of Mass and Rigidity")> _
    CentersofMassandRigidity

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Story Forces")> _
    StoryForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Story Stiffness")> _
    StoryStiffness

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Gravity Ratios")> _
    ShearGravityRatios

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Stiffness Gravity Ratios")> _
    StiffnessGravityRatios

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Shear Ratios In Dual Systems And Modifiers")> _
    FrameShearRatiosInDualSystemsAndModifiers

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Frame Overturning Moments In Dual Systems")> _
    FrameOverturningMomentsInDualSystems

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Total Energy Components")> _
    TotalEnergyComponents

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Tributary Area and LLRF")> _
    TributaryAreaandLLRF

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Section Cut Forces - Analysis")> _
    SectionCutForcesAnalysis

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Section Cut Forces - Design")> _
    SectionCutForcesDesign

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Column Forces")> _
    ColumnForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Beam Forces")> _
    BeamForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Brace Forces")> _
    BraceForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Forces")> _
    ShellForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shell Stresses")> _
    ShellStresses

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Pier Forces")> _
    PierForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Spandrel Forces")> _
    SpandrelForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Forces")> _
    LinkForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Link Deformations")> _
    LinkDeformations

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Panel Zone Forces")> _
    PanelZoneForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Panel Zone Deformations")> _
    PanelZoneDeformations

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Hinge States")> _
    HingeStates

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Fiber Hinge States")> _
    FiberHingeStates

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Fiber Hinge Fiber States")> _
    FiberHingeFiberStates

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Beam Energy/Virtual Work")> _
    BeamEnergyVirtualWork

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Column Energy/Virtual Work")> _
    ColumnEnergyVirtualWork

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Brace Energy/Virtual Work")> _
    BraceEnergyVirtualWork

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Floor Energy/Virtual Work")> _
    FloorEnergyVirtualWork

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Wall Energy/Virtual Work")> _
    WallEnergyVirtualWork

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("PBD Ratios - Panel Zones")> _
    PBDRatiosPanelZones

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - AISC 360-10")> _
    SteelFramePreferencesAISC36010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - AISC 360-05")> _
    SteelFramePreferencesAISC36005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - AISC ASD 89")> _
    SteelFramePreferencesAISCASD89

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - AISC LRFD 93")> _
    SteelFramePreferencesAISCLRFD93

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - AS 4100-1998")> _
    SteelFramePreferencesAS41001998

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - BS 5950-2000")> _
    SteelFramePreferencesBS59502000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - CSA S16-09")> _
    SteelFramePreferencesCSAS1609

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - Chinese 2010")> _
    SteelFramePreferencesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - Eurocode 3-2005")> _
    SteelFramePreferencesEurocode32005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - IS 800-2007")> _
    SteelFramePreferencesIS8002007

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - Italian NTC 2008")> _
    SteelFramePreferencesItalianNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Preferences - NZS 3404-1997")> _
    SteelFramePreferencesNZS34041997

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - ACI 318-11")> _
    ConcreteFramePreferencesACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - ACI 318-08")> _
    ConcreteFramePreferencesACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - AS 3600-09")> _
    ConcreteFramePreferencesAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - BS 8110-97")> _
    ConcreteFramePreferencesBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - Chinese 2010")> _
    ConcreteFramePreferencesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - CSA A23.3-04")> _
    ConcreteFramePreferencesCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - Eurocode 2-2004")> _
    ConcreteFramePreferencesEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - Hong Kong CP 2013")> _
    ConcreteFramePreferencesHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - Hong Kong CP 2004")> _
    ConcreteFramePreferencesHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - IS 456-2000")> _
    ConcreteFramePreferencesIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - Italian NTC 2008")> _
    ConcreteFramePreferencesItalianNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - KCI 1999")> _
    ConcreteFramePreferencesKCI1999

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - Mexican RCDF 2004")> _
    ConcreteFramePreferencesMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - NZS 3101-06")> _
    ConcreteFramePreferencesNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - Singapore CP 65-99")> _
    ConcreteFramePreferencesSingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Frame Preferences - TS 500-2000")> _
    ConcreteFramePreferencesTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - ACI 318-11")> _
    ShearWallPreferencesACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - ACI 530-11 Masonry")> _
    ShearWallPreferencesACI53011Masonry

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - ACI 318-08")> _
    ShearWallPreferencesACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - AS 3600-09")> _
    ShearWallPreferencesAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - BS 8110-97")> _
    ShearWallPreferencesBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - CSA A23.3-04")> _
    ShearWallPreferencesCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - Chinese 2010")> _
    ShearWallPreferencesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - Eurocode 2-2004")> _
    ShearWallPreferencesEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - Hong Kong CP 2013")> _
    ShearWallPreferencesHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - Hong Kong CP 2004")> _
    ShearWallPreferencesHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - IS 456-2000")> _
    ShearWallPreferencesIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - Mexican RCDF 2004")> _
    ShearWallPreferencesMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - NZS 3101-06")> _
    ShearWallPreferencesNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - Singapore CP 65:99")> _
    ShearWallPreferencesSingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Preferences - TS 500-2000")> _
    ShearWallPreferencesTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Preferences - AISC 360-10")> _
    CompositeBeamPreferencesAISC36010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Preferences - AISC 360-05")> _
    CompositeBeamPreferencesAISC36005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Preferences - BS 5950-90")> _
    CompositeBeamPreferencesBS595090

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Preferences - Chinese 2010")> _
    CompositeBeamPreferencesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Preferences - CSA S16-09")> _
    CompositeBeamPreferencesCSAS1609

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Preferences - Eurocode 4-2004")> _
    CompositeBeamPreferencesEurocode42004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Preferences - IS 800-1998")> _
    CompositeBeamPreferencesIS8001998

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Column Preferences - AISC 360-10")> _
    CompositeColumnPreferencesAISC36010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Column Preferences - Chinese 2010")> _
    CompositeColumnPreferencesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - AISC 360-10")> _
    SteelFrameOverwritesAISC36010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - AISC 360-05")> _
    SteelFrameOverwritesAISC36005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - AISC ASD 89")> _
    SteelFrameOverwritesAISCASD89

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - AISC LRFD 93")> _
    SteelFrameOverwritesAISCLRFD93

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - AS 4100-1998")> _
    SteelFrameOverwritesAS41001998

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - BS 5950-2000")> _
    SteelFrameOverwritesBS59502000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - Chinese 2010")> _
    SteelFrameOverwritesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - CSA S16-09")> _
    SteelFrameOverwritesCSAS1609

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - Eurocode 3-2005")> _
    SteelFrameOverwritesEurocode32005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - IS 800-2007")> _
    SteelFrameOverwritesIS8002007

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - Italian NTC 2008")> _
    SteelFrameOverwritesItalianNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Overwrites - NZS 3404-1997")> _
    SteelFrameOverwritesNZS34041997

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - ACI 318-11")> _
    ConcreteColumnOverwritesACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - ACI 318-08")> _
    ConcreteColumnOverwritesACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - AS 3600-09")> _
    ConcreteColumnOverwritesAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - BS 8110-97")> _
    ConcreteColumnOverwritesBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - Chinese 2010")> _
    ConcreteColumnOverwritesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - CSA A23.3-04")> _
    ConcreteColumnOverwritesCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - Eurocode 2-2004")> _
    ConcreteColumnOverwritesEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - Hong Kong CP 2013")> _
    ConcreteColumnOverwritesHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - Hong Kong CP 2004")> _
    ConcreteColumnOverwritesHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - IS 456-2000")> _
    ConcreteColumnOverwritesIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - Italian NTC 2008")> _
    ConcreteColumnOverwritesItalianNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - KCI 1999")> _
    ConcreteColumnOverwritesKCI1999

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - Mexican RCDF 2004")> _
    ConcreteColumnOverwritesMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - NZS 3101-06")> _
    ConcreteColumnOverwritesNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - Singapore CP 65-99")> _
    ConcreteColumnOverwritesSingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Overwrites - TS 500-2000")> _
    ConcreteColumnOverwritesTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - ACI 318-11")> _
    ConcreteBeamOverwritesACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - ACI 318-08")> _
    ConcreteBeamOverwritesACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - AS 3600-09")> _
    ConcreteBeamOverwritesAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - BS 8110-97")> _
    ConcreteBeamOverwritesBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - Chinese 2010")> _
    ConcreteBeamOverwritesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - CSA A23.3-04")> _
    ConcreteBeamOverwritesCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - Eurocode 2-2004")> _
    ConcreteBeamOverwritesEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - Hong Kong CP 2013")> _
    ConcreteBeamOverwritesHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - Hong Kong CP 2004")> _
    ConcreteBeamOverwritesHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - IS 456-2000")> _
    ConcreteBeamOverwritesIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - Italian NTC 2008")> _
    ConcreteBeamOverwritesItalianNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - KCI 1999")> _
    ConcreteBeamOverwritesKCI1999

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - Mexican RCDF 2004")> _
    ConcreteBeamOverwritesMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - NZS 3101-06")> _
    ConcreteBeamOverwritesNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - Singapore CP 65-99")> _
    ConcreteBeamOverwritesSingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Overwrites - TS 500-2000")> _
    ConcreteBeamOverwritesTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Overwrites - AISC 360-10")> _
    CompositeBeamOverwritesAISC36010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Overwrites - AISC 360-05")> _
    CompositeBeamOverwritesAISC36005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Overwrites - BS 5950-90")> _
    CompositeBeamOverwritesBS595090

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Overwrites - Chinese 2010")> _
    CompositeBeamOverwritesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Overwrites - CSA S16-09")> _
    CompositeBeamOverwritesCSAS1609

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Overwrites - Eurocode 4-2004")> _
    CompositeBeamOverwritesEurocode42004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Overwrites - IS 800-1998")> _
    CompositeBeamOverwritesIS8001998

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Column Overwrites - AISC 360-10")> _
    CompositeColumnOverwritesAISC36010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Column Overwrites - Chinese 2010")> _
    CompositeColumnOverwritesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - ACI 318-11")> _
    ShearWallPierOverwritesACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - ACI 530-11 Masonry")> _
    ShearWallPierOverwritesACI53011Masonry

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - ACI 318-08")> _
    ShearWallPierOverwritesACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - AS 3600-09")> _
    ShearWallPierOverwritesAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - BS 8110-97")> _
    ShearWallPierOverwritesBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - CSA A23.3-04")> _
    ShearWallPierOverwritesCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - Chinese 2010")> _
    ShearWallPierOverwritesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - Eurocode 2-2004")> _
    ShearWallPierOverwritesEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - Hong Kong CP 2013")> _
    ShearWallPierOverwritesHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - Hong Kong CP 2004")> _
    ShearWallPierOverwritesHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - IS 456-2000")> _
    ShearWallPierOverwritesIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - Mexican RCDF 2004")> _
    ShearWallPierOverwritesMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - NZS 3101-06")> _
    ShearWallPierOverwritesNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - Singapore CP 65:99")> _
    ShearWallPierOverwritesSingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Overwrites - TS 500-2000")> _
    ShearWallPierOverwritesTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - ACI 318-11")> _
    ShearWallSpandrelOverwritesACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - ACI 530-11 Masonry")> _
    ShearWallSpandrelOverwritesACI53011Masonry

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - ACI 318-08")> _
    ShearWallSpandrelOverwritesACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - AS 3600-09")> _
    ShearWallSpandrelOverwritesAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - BS 8110-97")> _
    ShearWallSpandrelOverwritesBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - CSA A23.3-04")> _
    ShearWallSpandrelOverwritesCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - Chinese 2010")> _
    ShearWallSpandrelOverwritesChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - Eurocode 2-2004")> _
    ShearWallSpandrelOverwritesEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - Hong Kong CP 2013")> _
    ShearWallSpandrelOverwritesHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - Hong Kong CP 2004")> _
    ShearWallSpandrelOverwritesHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - IS 456-2000")> _
    ShearWallSpandrelOverwritesIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - Mexican RCDF 2004")> _
    ShearWallSpandrelOverwritesMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - NZS 3101-06")> _
    ShearWallSpandrelOverwritesNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - Singapore CP 65:99")> _
    ShearWallSpandrelOverwritesSingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Overwrites - TS 500-2000")> _
    ShearWallSpandrelOverwritesTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Beam Design Forces")> _
    BeamDesignForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Column Design Forces")> _
    ColumnDesignForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Brace Design Forces")> _
    BraceDesignForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Pier Design Forces")> _
    PierDesignForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Spandrel Design Forces")> _
    SpandrelDesignForces

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Column Envelope")> _
    SteelColumnEnvelope

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Beam Envelope")> _
    SteelBeamEnvelope

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Brace Envelope")> _
    SteelBraceEnvelope

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - AISC 360-10")> _
    SteelFrameSummaryAISC36010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - AISC 360-05")> _
    SteelFrameSummaryAISC36005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - AISC ASD 89")> _
    SteelFrameSummaryAISCASD89

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - AISC LRFD 93")> _
    SteelFrameSummaryAISCLRFD93

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - AS 4100-1998")> _
    SteelFrameSummaryAS41001998

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - BS 5950-2000")> _
    SteelFrameSummaryBS59502000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - Chinese 2010")> _
    SteelFrameSummaryChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - CSA S16-09")> _
    SteelFrameSummaryCSAS1609

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - Eurocode 3-2005")> _
    SteelFrameSummaryEurocode32005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - IS 800-2007")> _
    SteelFrameSummaryIS8002007

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - Italian NTC 2008")> _
    SteelFrameSummaryItalianNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Steel Frame Summary - NZS 3404-1997")> _
    SteelFrameSummaryNZS34041997

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column PMM Envelope")> _
    ConcreteColumnPMMEnvelope

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Shear Envelope")> _
    ConcreteColumnShearEnvelope

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - ACI 318-11")> _
    ConcreteColumnSummaryACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - ACI 318-08")> _
    ConcreteColumnSummaryACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - AS 3600-09")> _
    ConcreteColumnSummaryAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - BS 8110-97")> _
    ConcreteColumnSummaryBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - Chinese 2010")> _
    ConcreteColumnSummaryChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - CSA A23.3-04")> _
    ConcreteColumnSummaryCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - Eurocode 2-2004")> _
    ConcreteColumnSummaryEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - Hong Kong CP 2013")> _
    ConcreteColumnSummaryHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - Hong Kong CP 2004")> _
    ConcreteColumnSummaryHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - IS 456-2000")> _
    ConcreteColumnSummaryIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - Italian NTC 2008")> _
    ConcreteColumnSummaryItalianNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - KCI 1999")> _
    ConcreteColumnSummaryKCI1999

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - Mexican RCDF 2004")> _
    ConcreteColumnSummaryMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - NZS 3101-06")> _
    ConcreteColumnSummaryNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - Singapore CP 65-99")> _
    ConcreteColumnSummarySingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Column Summary - TS 500-2000")> _
    ConcreteColumnSummaryTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Flexure Envelope")> _
    ConcreteBeamFlexureEnvelope

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Shear Envelope")> _
    ConcreteBeamShearEnvelope

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - ACI 318-11")> _
    ConcreteBeamSummaryACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - ACI 318-08")> _
    ConcreteBeamSummaryACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - AS 3600-09")> _
    ConcreteBeamSummaryAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - BS 8110-97")> _
    ConcreteBeamSummaryBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - Chinese 2010")> _
    ConcreteBeamSummaryChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - CSA A23.3-04")> _
    ConcreteBeamSummaryCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - Eurocode 2-2004")> _
    ConcreteBeamSummaryEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - Hong Kong CP 2013")> _
    ConcreteBeamSummaryHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - Hong Kong CP 2004")> _
    ConcreteBeamSummaryHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - IS 456-2000")> _
    ConcreteBeamSummaryIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - Italian NTC 2008")> _
    ConcreteBeamSummaryItalianNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - KCI 1999")> _
    ConcreteBeamSummaryKCI1999

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - Mexican RCDF 2004")> _
    ConcreteBeamSummaryMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - NZS 3101-06")> _
    ConcreteBeamSummaryNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - Singapore CP 65-99")> _
    ConcreteBeamSummarySingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Beam Summary - TS 500-2000")> _
    ConcreteBeamSummaryTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Envelope")> _
    ConcreteJointEnvelope

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - ACI 318-11")> _
    ConcreteJointSummaryACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - ACI 318-08")> _
    ConcreteJointSummaryACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - AS 3600-09")> _
    ConcreteJointSummaryAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - BS 8110-97")> _
    ConcreteJointSummaryBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - Chinese 2010")> _
    ConcreteJointSummaryChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - CSA A23.3-04")> _
    ConcreteJointSummaryCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - Eurocode 2-2004")> _
    ConcreteJointSummaryEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - Hong Kong CP 2013")> _
    ConcreteJointSummaryHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - Hong Kong CP 2004")> _
    ConcreteJointSummaryHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - IS 456-2000")> _
    ConcreteJointSummaryIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - Italian NTC 2008")> _
    ConcreteJointSummaryItalianNTC2008

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - KCI 1999")> _
    ConcreteJointSummaryKCI1999

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - Mexican RCDF 2004")> _
    ConcreteJointSummaryMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - NZS 3101-06")> _
    ConcreteJointSummaryNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - Singapore CP 65-99")> _
    ConcreteJointSummarySingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Concrete Joint Summary - TS 500-2000")> _
    ConcreteJointSummaryTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - ACI 318-11")> _
    ShearWallPierSummaryACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - ACI 530-11 Masonry")> _
    ShearWallPierSummaryACI53011Masonry

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - ACI 318-08")> _
    ShearWallPierSummaryACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - AS 3600-09")> _
    ShearWallPierSummaryAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - BS 8110-97")> _
    ShearWallPierSummaryBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - CSA A23.3-04")> _
    ShearWallPierSummaryCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - Chinese 2010")> _
    ShearWallPierSummaryChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - Eurocode 2-2004")> _
    ShearWallPierSummaryEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - Hong Kong CP 2013")> _
    ShearWallPierSummaryHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - Hong Kong CP 2004")> _
    ShearWallPierSummaryHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - IS 456-2000")> _
    ShearWallPierSummaryIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - Mexican RCDF 2004")> _
    ShearWallPierSummaryMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - NZS 3101-06")> _
    ShearWallPierSummaryNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - Singapore CP 65:99")> _
    ShearWallPierSummarySingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Pier Summary - TS 500-2000")> _
    ShearWallPierSummaryTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - ACI 318-11")> _
    ShearWallSpandrelSummaryACI31811

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - ACI 530-11 Masonry")> _
    ShearWallSpandrelSummaryACI53011Masonry

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - ACI 318-08")> _
    ShearWallSpandrelSummaryACI31808

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - AS 3600-09")> _
    ShearWallSpandrelSummaryAS360009

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - BS 8110-97")> _
    ShearWallSpandrelSummaryBS811097

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - CSA A23.3-04")> _
    ShearWallSpandrelSummaryCSAA23304

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - Chinese 2010")> _
    ShearWallSpandrelSummaryChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - Eurocode 2-2004")> _
    ShearWallSpandrelSummaryEurocode22004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - Hong Kong CP 2013")> _
    ShearWallSpandrelSummaryHongKongCP2013

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - Hong Kong CP 2004")> _
    ShearWallSpandrelSummaryHongKongCP2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - IS 456-2000")> _
    ShearWallSpandrelSummaryIS4562000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - Mexican RCDF 2004")> _
    ShearWallSpandrelSummaryMexicanRCDF2004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - NZS 3101-06")> _
    ShearWallSpandrelSummaryNZS310106

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - Singapore CP 65:99")> _
    ShearWallSpandrelSummarySingaporeCP6599

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Shear Wall Spandrel Summary - TS 500-2000")> _
    ShearWallSpandrelSummaryTS5002000

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Envelope")> _
    CompositeBeamEnvelope

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Summary - AISC 360-10")> _
    CompositeBeamSummaryAISC36010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Summary - AISC 360-05")> _
    CompositeBeamSummaryAISC36005

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Summary - BS 5950-90")> _
    CompositeBeamSummaryBS595090

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Summary - Chinese 2010")> _
    CompositeBeamSummaryChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Summary - CSA S16-09")> _
    CompositeBeamSummaryCSAS1609

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Summary - Eurocode 4-2004")> _
    CompositeBeamSummaryEurocode42004

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Beam Summary - IS 800-1998")> _
    CompositeBeamSummaryIS8001998

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Column Encased Summary - AISC 360-10")> _
    CompositeColumnEncasedSummaryAISC36010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Column Filled Summary - AISC 360-10")> _
    CompositeColumnFilledSummaryAISC36010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Column Encased Summary - Chinese 2010")> _
    CompositeColumnEncasedSummaryChinese2010

    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Composite Column Filled Summary - Chinese 2010")> _
    CompositeColumnFilledSummaryChinese2010
End Enum
