'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.17929.
'
Namespace RegTest
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class regtest
        
        Private generalField As general
        
        Private actionsField As actions
        
        Private testingField As testing
        
        Private job_tasklist_definitionsField As job_tasklist_definitions
        
        Private distributed_testingField As distributed_testing
        
        Private reportingField As reporting
        
        Private gui_dataField As gui_data
        
        Private advancedField As advanced
        
        Private experimentalField As Object
        
        '''<remarks/>
        Public Property general() As general
            Get
                Return Me.generalField
            End Get
            Set
                Me.generalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property actions() As actions
            Get
                Return Me.actionsField
            End Get
            Set
                Me.actionsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property testing() As testing
            Get
                Return Me.testingField
            End Get
            Set
                Me.testingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property job_tasklist_definitions() As job_tasklist_definitions
            Get
                Return Me.job_tasklist_definitionsField
            End Get
            Set
                Me.job_tasklist_definitionsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property distributed_testing() As distributed_testing
            Get
                Return Me.distributed_testingField
            End Get
            Set
                Me.distributed_testingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property reporting() As reporting
            Get
                Return Me.reportingField
            End Get
            Set
                Me.reportingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property gui_data() As gui_data
            Get
                Return Me.gui_dataField
            End Get
            Set
                Me.gui_dataField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property advanced() As advanced
            Get
                Return Me.advancedField
            End Get
            Set
                Me.advancedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property experimental() As Object
            Get
                Return Me.experimentalField
            End Get
            Set
                Me.experimentalField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class general
        
        Private models_database_directoryField As generalModels_database_directory
        
        Private models_run_directoryField As generalModels_run_directory
        
        Private output_directoryField As generalOutput_directory
        
        Private programs_root_directoryField As generalPrograms_root_directory
        
        Private computer_idField As Object
        
        Private computer_descriptionField As Object
        
        Private write_log_filesField As yes_no
        
        '''<remarks/>
        Public Property models_database_directory() As generalModels_database_directory
            Get
                Return Me.models_database_directoryField
            End Get
            Set
                Me.models_database_directoryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property models_run_directory() As generalModels_run_directory
            Get
                Return Me.models_run_directoryField
            End Get
            Set
                Me.models_run_directoryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property output_directory() As generalOutput_directory
            Get
                Return Me.output_directoryField
            End Get
            Set
                Me.output_directoryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property programs_root_directory() As generalPrograms_root_directory
            Get
                Return Me.programs_root_directoryField
            End Get
            Set
                Me.programs_root_directoryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property computer_id() As Object
            Get
                Return Me.computer_idField
            End Get
            Set
                Me.computer_idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property computer_description() As Object
            Get
                Return Me.computer_descriptionField
            End Get
            Set
                Me.computer_descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property write_log_files() As yes_no
            Get
                Return Me.write_log_filesField
            End Get
            Set
                Me.write_log_filesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com")>  _
    Partial Public Class generalModels_database_directory
        
        Private pathField As path1
        
        '''<remarks/>
        Public Property path() As path1
            Get
                Return Me.pathField
            End Get
            Set
                Me.pathField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute("path", [Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class path1
        
        Private typeField As absolute_relative
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property type() As absolute_relative
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")>  _
    Public Enum absolute_relative
        
        '''<remarks/>
        absolute
        
        '''<remarks/>
        relative
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiamerica.com")>  _
    Partial Public Class directory_path_with_optional_subdirectory
        
        Private typeField As absolute_relative
        
        Private create_subdirectory_named_as_test_idField As yes_no
        
        Private terminate_if_subdirectory_existsField As yes_no
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property type() As absolute_relative
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property create_subdirectory_named_as_test_id() As yes_no
            Get
                Return Me.create_subdirectory_named_as_test_idField
            End Get
            Set
                Me.create_subdirectory_named_as_test_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property terminate_if_subdirectory_exists() As yes_no
            Get
                Return Me.terminate_if_subdirectory_existsField
            End Get
            Set
                Me.terminate_if_subdirectory_existsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")>  _
    Public Enum yes_no
        
        '''<remarks/>
        yes
        
        '''<remarks/>
        no
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class contour
        
        Private min_value_exclusiveField As Object
        
        Private max_value_inclusiveField As Object
        
        Private td_css_classField As Object
        
        Private legend_descriptionField As Object
        
        Private legend_commentField As Object
        
        '''<remarks/>
        Public Property min_value_exclusive() As Object
            Get
                Return Me.min_value_exclusiveField
            End Get
            Set
                Me.min_value_exclusiveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property max_value_inclusive() As Object
            Get
                Return Me.max_value_inclusiveField
            End Get
            Set
                Me.max_value_inclusiveField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property td_css_class() As Object
            Get
                Return Me.td_css_classField
            End Get
            Set
                Me.td_css_classField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property legend_description() As Object
            Get
                Return Me.legend_descriptionField
            End Get
            Set
                Me.legend_descriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property legend_comment() As Object
            Get
                Return Me.legend_commentField
            End Get
            Set
                Me.legend_commentField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com")>  _
    Partial Public Class generalModels_run_directory
        
        Private pathField As directory_path_with_optional_subdirectory
        
        '''<remarks/>
        Public Property path() As directory_path_with_optional_subdirectory
            Get
                Return Me.pathField
            End Get
            Set
                Me.pathField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com")>  _
    Partial Public Class generalOutput_directory
        
        Private pathField As directory_path_with_optional_subdirectory
        
        Private same_as_models_run_directoryField As yes_no
        
        '''<remarks/>
        Public Property path() As directory_path_with_optional_subdirectory
            Get
                Return Me.pathField
            End Get
            Set
                Me.pathField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property same_as_models_run_directory() As yes_no
            Get
                Return Me.same_as_models_run_directoryField
            End Get
            Set
                Me.same_as_models_run_directoryField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com")>  _
    Partial Public Class generalPrograms_root_directory
        
        Private pathField As path1
        
        '''<remarks/>
        Public Property path() As path1
            Get
                Return Me.pathField
            End Get
            Set
                Me.pathField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class actions
        
        Private update_test_definition_to_use_latest_buildField As update_test_definition_to_use_latest_build
        
        Private autogenerate_test_idField As autogenerate_test_id
        
        Private copy_modelsField As copy_models
        
        Private copy_models_flatField As copy_models_flat
        
        Private copy_models_mirrorField As copy_models_mirror
        
        Private write_xml_files_listField As write_xml_files_list
        
        Private run_local_testField As run_local_test
        
        Private start_distributed_testField As start_distributed_test
        
        Private join_distributed_testField As join_distributed_test
        
        Private run_jobField As run_job
        
        '''<remarks/>
        Public Property update_test_definition_to_use_latest_build() As update_test_definition_to_use_latest_build
            Get
                Return Me.update_test_definition_to_use_latest_buildField
            End Get
            Set
                Me.update_test_definition_to_use_latest_buildField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property autogenerate_test_id() As autogenerate_test_id
            Get
                Return Me.autogenerate_test_idField
            End Get
            Set
                Me.autogenerate_test_idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property copy_models() As copy_models
            Get
                Return Me.copy_modelsField
            End Get
            Set
                Me.copy_modelsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property copy_models_flat() As copy_models_flat
            Get
                Return Me.copy_models_flatField
            End Get
            Set
                Me.copy_models_flatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property copy_models_mirror() As copy_models_mirror
            Get
                Return Me.copy_models_mirrorField
            End Get
            Set
                Me.copy_models_mirrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property write_xml_files_list() As write_xml_files_list
            Get
                Return Me.write_xml_files_listField
            End Get
            Set
                Me.write_xml_files_listField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property run_local_test() As run_local_test
            Get
                Return Me.run_local_testField
            End Get
            Set
                Me.run_local_testField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property start_distributed_test() As start_distributed_test
            Get
                Return Me.start_distributed_testField
            End Get
            Set
                Me.start_distributed_testField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property join_distributed_test() As join_distributed_test
            Get
                Return Me.join_distributed_testField
            End Get
            Set
                Me.join_distributed_testField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property run_job() As run_job
            Get
                Return Me.run_jobField
            End Get
            Set
                Me.run_jobField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class update_test_definition_to_use_latest_build
        
        Private runField As yes_no
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property run() As yes_no
            Get
                Return Me.runField
            End Get
            Set
                Me.runField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class autogenerate_test_id
        
        Private suffixField As String
        
        Private runField As yes_no
        
        '''<remarks/>
        Public Property suffix() As String
            Get
                Return Me.suffixField
            End Get
            Set
                Me.suffixField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property run() As yes_no
            Get
                Return Me.runField
            End Get
            Set
                Me.runField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class copy_models
        
        Private runField As yes_no
        
        Private reuse_xml_filelistField As yes_no
        
        Private create_subdirectories_named_as_classificationField As yes_no
        
        Private copy_current_test_models_onlyField As yes_no
        
        Private copy_model_files_onlyField As yes_no
        
        Private translate_model_xml_filesField As yes_no
        
        Private copy_selection_onlyField As yes_no
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property run() As yes_no
            Get
                Return Me.runField
            End Get
            Set
                Me.runField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property reuse_xml_filelist() As yes_no
            Get
                Return Me.reuse_xml_filelistField
            End Get
            Set
                Me.reuse_xml_filelistField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property create_subdirectories_named_as_classification() As yes_no
            Get
                Return Me.create_subdirectories_named_as_classificationField
            End Get
            Set
                Me.create_subdirectories_named_as_classificationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property copy_current_test_models_only() As yes_no
            Get
                Return Me.copy_current_test_models_onlyField
            End Get
            Set
                Me.copy_current_test_models_onlyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property copy_model_files_only() As yes_no
            Get
                Return Me.copy_model_files_onlyField
            End Get
            Set
                Me.copy_model_files_onlyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property translate_model_xml_files() As yes_no
            Get
                Return Me.translate_model_xml_filesField
            End Get
            Set
                Me.translate_model_xml_filesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property copy_selection_only() As yes_no
            Get
                Return Me.copy_selection_onlyField
            End Get
            Set
                Me.copy_selection_onlyField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class copy_models_flat
        
        Private custom_model_file_directory_pathField As copy_models_flatCustom_model_file_directory_path
        
        Private runField As yes_no
        
        Private reuse_xml_filelistField As yes_no

        Private dry_runField As yes_no

        Private replace_model_ids_by_sequential_numbersField As yes_no

        Private translate_model_xml_filesField As yes_no

        '''<remarks/>
        Public Property custom_model_file_directory_path() As copy_models_flatCustom_model_file_directory_path
            Get
                Return Me.custom_model_file_directory_pathField
            End Get
            Set(value As copy_models_flatCustom_model_file_directory_path)
                Me.custom_model_file_directory_pathField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property run() As yes_no
            Get
                Return Me.runField
            End Get
            Set(value As yes_no)
                Me.runField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property reuse_xml_filelist() As yes_no
            Get
                Return Me.reuse_xml_filelistField
            End Get
            Set(value As yes_no)
                Me.reuse_xml_filelistField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property dry_run() As yes_no
            Get
                Return Me.dry_runField
            End Get
            Set(value As yes_no)
                Me.dry_runField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property replace_model_ids_by_sequential_numbers() As yes_no
            Get
                Return Me.replace_model_ids_by_sequential_numbersField
            End Get
            Set(value As yes_no)
                Me.replace_model_ids_by_sequential_numbersField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property translate_model_xml_files() As yes_no
            Get
                Return Me.translate_model_xml_filesField
            End Get
            Set(value As yes_no)
                Me.translate_model_xml_filesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class copy_models_flatCustom_model_file_directory_path

        Private typeField As absolute_relative

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property type() As absolute_relative
            Get
                Return Me.typeField
            End Get
            Set(value As absolute_relative)
                Me.typeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class copy_models_mirror

        Private runField As yes_no

        Private translate_model_xml_filesField As yes_no

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property run() As yes_no
            Get
                Return Me.runField
            End Get
            Set(value As yes_no)
                Me.runField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property translate_model_xml_files() As yes_no
            Get
                Return Me.translate_model_xml_filesField
            End Get
            Set(value As yes_no)
                Me.translate_model_xml_filesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class write_xml_files_list

        Private runField As yes_no

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property run() As yes_no
            Get
                Return Me.runField
            End Get
            Set(value As yes_no)
                Me.runField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class run_local_test

        Private runField As yes_no

        Private run_using_batch_fileField As yes_no

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property run() As yes_no
            Get
                Return Me.runField
            End Get
            Set(value As yes_no)
                Me.runField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property run_using_batch_file() As yes_no
            Get
                Return Me.run_using_batch_fileField
            End Get
            Set(value As yes_no)
                Me.run_using_batch_fileField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class start_distributed_test

        Private runField As yes_no

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property run() As yes_no
            Get
                Return Me.runField
            End Get
            Set(value As yes_no)
                Me.runField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class join_distributed_test

        Private runField As yes_no

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property run() As yes_no
            Get
                Return Me.runField
            End Get
            Set(value As yes_no)
                Me.runField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class run_job

        Private test_typeField As run_job_test_type

        Private tasklist_typeField As tasklist_type

        Private runField As yes_no

        '''<remarks/>
        Public Property test_type() As run_job_test_type
            Get
                Return Me.test_typeField
            End Get
            Set(value As run_job_test_type)
                Me.test_typeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property tasklist_type() As tasklist_type
            Get
                Return Me.tasklist_typeField
            End Get
            Set(value As tasklist_type)
                Me.tasklist_typeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property run() As yes_no
            Get
                Return Me.runField
            End Get
            Set(value As yes_no)
                Me.runField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum run_job_test_type

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("distributed test with local control")> _
        distributedtestwithlocalcontrol
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum tasklist_type

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("dynamic continuous tasklist")> _
        dynamiccontinuoustasklist
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class testing

        Private test_idField As Object

        Private test_descriptionField As Object

        Private test_to_runField As test_to_run

        Private programField As program

        Private command_lineField As Object

        Private selectionsField As selections

        Private previous_test_results_fileField As previous_test_results_file

        Private runtime_limit_overwritesField As runtime_limit_overwrites

        Private email_notificationsField As email_notifications

        '''<remarks/>
        Public Property test_id() As Object
            Get
                Return Me.test_idField
            End Get
            Set(value As Object)
                Me.test_idField = value
            End Set
        End Property

        '''<remarks/>
        Public Property test_description() As Object
            Get
                Return Me.test_descriptionField
            End Get
            Set(value As Object)
                Me.test_descriptionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property test_to_run() As test_to_run
            Get
                Return Me.test_to_runField
            End Get
            Set(value As test_to_run)
                Me.test_to_runField = value
            End Set
        End Property

        '''<remarks/>
        Public Property program() As program
            Get
                Return Me.programField
            End Get
            Set(value As program)
                Me.programField = value
            End Set
        End Property

        '''<remarks/>
        Public Property command_line() As Object
            Get
                Return Me.command_lineField
            End Get
            Set(value As Object)
                Me.command_lineField = value
            End Set
        End Property

        '''<remarks/>
        Public Property selections() As selections
            Get
                Return Me.selectionsField
            End Get
            Set(value As selections)
                Me.selectionsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property previous_test_results_file() As previous_test_results_file
            Get
                Return Me.previous_test_results_fileField
            End Get
            Set(value As previous_test_results_file)
                Me.previous_test_results_fileField = value
            End Set
        End Property

        '''<remarks/>
        Public Property runtime_limit_overwrites() As runtime_limit_overwrites
            Get
                Return Me.runtime_limit_overwritesField
            End Get
            Set(value As runtime_limit_overwrites)
                Me.runtime_limit_overwritesField = value
            End Set
        End Property

        '''<remarks/>
        Public Property email_notifications() As email_notifications
            Get
                Return Me.email_notificationsField
            End Get
            Set(value As email_notifications)
                Me.email_notificationsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class test_to_run

        Private dry_runField As yes_no

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property dry_run() As yes_no
            Get
                Return Me.dry_runField
            End Get
            Set(value As yes_no)
                Me.dry_runField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class program

        Private nameField As program_name

        Private versionField As Object

        Private buildField As Object

        Private pathField As programPath

        '''<remarks/>
        Public Property name() As program_name
            Get
                Return Me.nameField
            End Get
            Set(value As program_name)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property version() As Object
            Get
                Return Me.versionField
            End Get
            Set(value As Object)
                Me.versionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property build() As Object
            Get
                Return Me.buildField
            End Get
            Set(value As Object)
                Me.buildField = value
            End Set
        End Property

        '''<remarks/>
        Public Property path() As programPath
            Get
                Return Me.pathField
            End Get
            Set(value As programPath)
                Me.pathField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum program_name

        '''<remarks/>
        SAP2000

        '''<remarks/>
        CSiBridge

        '''<remarks/>
        ETABS

        '''<remarks/>
        SAFE

        '''<remarks/>
        Perform3D
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class programPath

        Private typeField As absolute_relative

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property type() As absolute_relative
            Get
                Return Me.typeField
            End Get
            Set(value As absolute_relative)
                Me.typeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class selections

        Private keywordsField As selectionsKeywords

        Private keywords_exclusiveField As selectionsKeywords_exclusive

        Private model_idsField As selectionsModel_ids

        Private model_id_rangeField As selectionsModel_id_range

        Private runtime_rangeField As selectionsRuntime_range

        Private programField As selectionsProgram

        Private model_file_extensionsField As selectionsModel_file_extensions

        '''<remarks/>
        Public Property keywords() As selectionsKeywords
            Get
                Return Me.keywordsField
            End Get
            Set(value As selectionsKeywords)
                Me.keywordsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property keywords_exclusive() As selectionsKeywords_exclusive
            Get
                Return Me.keywords_exclusiveField
            End Get
            Set(value As selectionsKeywords_exclusive)
                Me.keywords_exclusiveField = value
            End Set
        End Property

        '''<remarks/>
        Public Property model_ids() As selectionsModel_ids
            Get
                Return Me.model_idsField
            End Get
            Set(value As selectionsModel_ids)
                Me.model_idsField = value
            End Set
        End Property

        '''<remarks/>
        Public Property model_id_range() As selectionsModel_id_range
            Get
                Return Me.model_id_rangeField
            End Get
            Set(value As selectionsModel_id_range)
                Me.model_id_rangeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property runtime_range() As selectionsRuntime_range
            Get
                Return Me.runtime_rangeField
            End Get
            Set(value As selectionsRuntime_range)
                Me.runtime_rangeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property program() As selectionsProgram
            Get
                Return Me.programField
            End Get
            Set(value As selectionsProgram)
                Me.programField = value
            End Set
        End Property

        '''<remarks/>
        Public Property model_file_extensions() As selectionsModel_file_extensions
            Get
                Return Me.model_file_extensionsField
            End Get
            Set(value As selectionsModel_file_extensions)
                Me.model_file_extensionsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class selectionsKeywords

        Private keywordField() As Object

        Private useField As yes_no

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("keyword")> _
        Public Property keyword() As Object()
            Get
                Return Me.keywordField
            End Get
            Set(value As Object())
                Me.keywordField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property use() As yes_no
            Get
                Return Me.useField
            End Get
            Set(value As yes_no)
                Me.useField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class selectionsKeywords_exclusive

        Private keywordField() As Object

        Private useField As yes_no

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("keyword")> _
        Public Property keyword() As Object()
            Get
                Return Me.keywordField
            End Get
            Set(value As Object())
                Me.keywordField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property use() As yes_no
            Get
                Return Me.useField
            End Get
            Set(value As yes_no)
                Me.useField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class selectionsModel_ids

        Private model_idField() As Object

        Private useField As yes_no

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("model_id")> _
        Public Property model_id() As Object()
            Get
                Return Me.model_idField
            End Get
            Set(value As Object())
                Me.model_idField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property use() As yes_no
            Get
                Return Me.useField
            End Get
            Set(value As yes_no)
                Me.useField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class selectionsModel_id_range

        Private min_model_idField As Object

        Private max_model_idField As Object

        Private useField As yes_no

        '''<remarks/>
        Public Property min_model_id() As Object
            Get
                Return Me.min_model_idField
            End Get
            Set(value As Object)
                Me.min_model_idField = value
            End Set
        End Property

        '''<remarks/>
        Public Property max_model_id() As Object
            Get
                Return Me.max_model_idField
            End Get
            Set(value As Object)
                Me.max_model_idField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property use() As yes_no
            Get
                Return Me.useField
            End Get
            Set(value As yes_no)
                Me.useField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class selectionsRuntime_range

        Private min_runtimeField As selectionsRuntime_rangeMin_runtime

        Private max_runtimeField As selectionsRuntime_rangeMax_runtime

        Private useField As yes_no

        '''<remarks/>
        Public Property min_runtime() As selectionsRuntime_rangeMin_runtime
            Get
                Return Me.min_runtimeField
            End Get
            Set(value As selectionsRuntime_rangeMin_runtime)
                Me.min_runtimeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property max_runtime() As selectionsRuntime_rangeMax_runtime
            Get
                Return Me.max_runtimeField
            End Get
            Set(value As selectionsRuntime_rangeMax_runtime)
                Me.max_runtimeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property use() As yes_no
            Get
                Return Me.useField
            End Get
            Set(value As yes_no)
                Me.useField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class selectionsRuntime_rangeMin_runtime

        Private minutesField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> _
        Public Property minutes() As String
            Get
                Return Me.minutesField
            End Get
            Set(value As String)
                Me.minutesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class selectionsRuntime_rangeMax_runtime

        Private minutesField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> _
        Public Property minutes() As String
            Get
                Return Me.minutesField
            End Get
            Set(value As String)
                Me.minutesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class selectionsProgram

        Private nameField As Object

        Private useField As yes_no

        '''<remarks/>
        Public Property name() As Object
            Get
                Return Me.nameField
            End Get
            Set(value As Object)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property use() As yes_no
            Get
                Return Me.useField
            End Get
            Set(value As yes_no)
                Me.useField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class selectionsModel_file_extensions

        Private extensionField() As file_extensions_main

        Private useField As yes_no

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("extension")> _
        Public Property extension() As file_extensions_main()
            Get
                Return Me.extensionField
            End Get
            Set(value As file_extensions_main())
                Me.extensionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property use() As yes_no
            Get
                Return Me.useField
            End Get
            Set(value As yes_no)
                Me.useField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")> _
    Public Enum file_extensions_main

        '''<remarks/>
        sdb

        '''<remarks/>
        bdb

        '''<remarks/>
        edb

        '''<remarks/>
        fdb
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class previous_test_results_file

        Private pathField As path1

        '''<remarks/>
        Public Property path() As path1
            Get
                Return Me.pathField
            End Get
            Set(value As path1)
                Me.pathField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class runtime_limit_overwrites

        Private multiplierField As Double

        Private maximum_permitted_runtimeField As runtime_limit_overwritesMaximum_permitted_runtime

        '''<remarks/>
        Public Property multiplier() As Double
            Get
                Return Me.multiplierField
            End Get
            Set(value As Double)
                Me.multiplierField = value
            End Set
        End Property

        '''<remarks/>
        Public Property maximum_permitted_runtime() As runtime_limit_overwritesMaximum_permitted_runtime
            Get
                Return Me.maximum_permitted_runtimeField
            End Get
            Set(value As runtime_limit_overwritesMaximum_permitted_runtime)
                Me.maximum_permitted_runtimeField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class runtime_limit_overwritesMaximum_permitted_runtime

        Private minutesField As Double

        '''<remarks/>
        Public Property minutes() As Double
            Get
                Return Me.minutesField
            End Get
            Set(value As Double)
                Me.minutesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class email_notifications

        Private email_addressesField() As Object

        Private useField As yes_no

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("email_address", IsNullable:=False)> _
        Public Property email_addresses() As Object()
            Get
                Return Me.email_addressesField
            End Get
            Set(value As Object())
                Me.email_addressesField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property use() As yes_no
            Get
                Return Me.useField
            End Get
            Set(value As yes_no)
                Me.useField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class job_tasklist_definitions

        Private static_tasklistField As Object

        Private dynamic_initial_tasklistField As Object

        Private dynamic_continuous_tasklistField As dynamic_continuous_tasklist

        '''<remarks/>
        Public Property static_tasklist() As Object
            Get
                Return Me.static_tasklistField
            End Get
            Set(value As Object)
                Me.static_tasklistField = value
            End Set
        End Property

        '''<remarks/>
        Public Property dynamic_initial_tasklist() As Object
            Get
                Return Me.dynamic_initial_tasklistField
            End Get
            Set(value As Object)
                Me.dynamic_initial_tasklistField = value
            End Set
        End Property

        '''<remarks/>
        Public Property dynamic_continuous_tasklist() As dynamic_continuous_tasklist
            Get
                Return Me.dynamic_continuous_tasklistField
            End Get
            Set(value As dynamic_continuous_tasklist)
                Me.dynamic_continuous_tasklistField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class dynamic_continuous_tasklist

        Private watch_intervalField As dynamic_continuous_tasklistWatch_interval

        Private programsField() As dynamic_continuous_tasklistProgram

        '''<remarks/>
        Public Property watch_interval() As dynamic_continuous_tasklistWatch_interval
            Get
                Return Me.watch_intervalField
            End Get
            Set(value As dynamic_continuous_tasklistWatch_interval)
                Me.watch_intervalField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("program", IsNullable:=False)> _
        Public Property programs() As dynamic_continuous_tasklistProgram()
            Get
                Return Me.programsField
            End Get
            Set(value As dynamic_continuous_tasklistProgram())
                Me.programsField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class dynamic_continuous_tasklistWatch_interval

        Private minutesField As Double

        '''<remarks/>
        Public Property minutes() As Double
            Get
                Return Me.minutesField
            End Get
            Set(value As Double)
                Me.minutesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class dynamic_continuous_tasklistProgram

        Private nameField As program_name

        Private build_sort_key_rangeField As dynamic_continuous_tasklistProgramBuild_sort_key_range

        Private test_typesField() As String

        Private test_id_suffixField As String

        Private overwritesField() As dynamic_continuous_tasklistProgramOverwrite

        '''<remarks/>
        Public Property name() As program_name
            Get
                Return Me.nameField
            End Get
            Set(value As program_name)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property build_sort_key_range() As dynamic_continuous_tasklistProgramBuild_sort_key_range
            Get
                Return Me.build_sort_key_rangeField
            End Get
            Set(value As dynamic_continuous_tasklistProgramBuild_sort_key_range)
                Me.build_sort_key_rangeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("tests_no_empty", IsNullable:=False)> _
        Public Property test_types() As String()
            Get
                Return Me.test_typesField
            End Get
            Set(value As String())
                Me.test_typesField = value
            End Set
        End Property

        '''<remarks/>
        Public Property test_id_suffix() As String
            Get
                Return Me.test_id_suffixField
            End Get
            Set(value As String)
                Me.test_id_suffixField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("overwrite", IsNullable:=False)> _
        Public Property overwrites() As dynamic_continuous_tasklistProgramOverwrite()
            Get
                Return Me.overwritesField
            End Get
            Set(value As dynamic_continuous_tasklistProgramOverwrite())
                Me.overwritesField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class dynamic_continuous_tasklistProgramBuild_sort_key_range

        Private min_build_sort_keyField As Double

        Private max_build_sort_keyField As Double

        '''<remarks/>
        Public Property min_build_sort_key() As Double
            Get
                Return Me.min_build_sort_keyField
            End Get
            Set(value As Double)
                Me.min_build_sort_keyField = value
            End Set
        End Property

        '''<remarks/>
        Public Property max_build_sort_key() As Double
            Get
                Return Me.max_build_sort_keyField
            End Get
            Set(value As Double)
                Me.max_build_sort_keyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com")> _
    Partial Public Class dynamic_continuous_tasklistProgramOverwrite

        Private elementField As String

        Private valueField As String

        '''<remarks/>
        Public Property element() As String
            Get
                Return Me.elementField
            End Get
            Set(value As String)
                Me.elementField = value
            End Set
        End Property

        '''<remarks/>
        Public Property value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.csiamerica.com"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=False)> _
    Partial Public Class distributed_testing

        Private server_base_urlField As String

        Private models_sourceField As models_source

        '''<remarks/>
        Public Property server_base_url() As String
            Get
                Return Me.server_base_urlField
            End Get
            Set(value As String)
                Me.server_base_urlField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property models_source() As models_source
            Get
                Return Me.models_sourceField
            End Get
            Set(value As models_source)
                Me.models_sourceField = Value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Public Enum models_source
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("local models database")>  _
        localmodelsdatabase
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("download from server")>  _
        downloadfromserver
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class reporting
        
        Private model_results_table_cells_color_codingField As model_results_table_cells_color_coding
        
        Private percent_difference_decimal_digitsField As Object
        
        Private xml_stylesheet_filesField As xml_stylesheet_files
        
        '''<remarks/>
        Public Property model_results_table_cells_color_coding() As model_results_table_cells_color_coding
            Get
                Return Me.model_results_table_cells_color_codingField
            End Get
            Set
                Me.model_results_table_cells_color_codingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property percent_difference_decimal_digits() As Object
            Get
                Return Me.percent_difference_decimal_digitsField
            End Get
            Set
                Me.percent_difference_decimal_digitsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property xml_stylesheet_files() As xml_stylesheet_files
            Get
                Return Me.xml_stylesheet_filesField
            End Get
            Set
                Me.xml_stylesheet_filesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class model_results_table_cells_color_coding
        
        Private absolute_percent_difference_from_benchmark_or_last_best_value_if_availableField() As contour
        
        Private absolute_percent_difference_from_theoreticalField() As contour
        
        Private total_run_time_change_ratioField() As contour
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("contour", IsNullable:=false)>  _
        Public Property absolute_percent_difference_from_benchmark_or_last_best_value_if_available() As contour()
            Get
                Return Me.absolute_percent_difference_from_benchmark_or_last_best_value_if_availableField
            End Get
            Set
                Me.absolute_percent_difference_from_benchmark_or_last_best_value_if_availableField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("contour", IsNullable:=false)>  _
        Public Property absolute_percent_difference_from_theoretical() As contour()
            Get
                Return Me.absolute_percent_difference_from_theoreticalField
            End Get
            Set
                Me.absolute_percent_difference_from_theoreticalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("contour", IsNullable:=false)>  _
        Public Property total_run_time_change_ratio() As contour()
            Get
                Return Me.total_run_time_change_ratioField
            End Get
            Set
                Me.total_run_time_change_ratioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class xml_stylesheet_files
        
        Private test_resultsField As xml_stylesheet_filesTest_results
        
        '''<remarks/>
        Public Property test_results() As xml_stylesheet_filesTest_results
            Get
                Return Me.test_resultsField
            End Get
            Set
                Me.test_resultsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com")>  _
    Partial Public Class xml_stylesheet_filesTest_results
        
        Private pathField As xml_stylesheet_filesTest_resultsPath
        
        '''<remarks/>
        Public Property path() As xml_stylesheet_filesTest_resultsPath
            Get
                Return Me.pathField
            End Get
            Set
                Me.pathField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com")>  _
    Partial Public Class xml_stylesheet_filesTest_resultsPath
        
        Private typeField As absolute_relative
        
        Private valueField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property type() As absolute_relative
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set
                Me.valueField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class gui_data
        
        Private solver_optionsField As solver_options
        
        Private analysis_optionsField As analysis_options
        
        Private force_32_bitField As yes_no
        
        Private run_using_batch_fileField As yes_no
        
        '''<remarks/>
        Public Property solver_options() As solver_options
            Get
                Return Me.solver_optionsField
            End Get
            Set
                Me.solver_optionsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property analysis_options() As analysis_options
            Get
                Return Me.analysis_optionsField
            End Get
            Set
                Me.analysis_optionsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property force_32_bit() As yes_no
            Get
                Return Me.force_32_bitField
            End Get
            Set
                Me.force_32_bitField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property run_using_batch_file() As yes_no
            Get
                Return Me.run_using_batch_fileField
            End Get
            Set
                Me.run_using_batch_fileField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")>  _
    Public Enum solver_options
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("standard solver")>  _
        standardsolver
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("advanced solver")>  _
        advancedsolver
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("multi-threaded solver")>  _
        multithreadedsolver
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.csiberkeley.com/resources")>  _
    Public Enum analysis_options
        
        '''<remarks/>
        [auto]
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("gui process")>  _
        guiprocess
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("separate process")>  _
        separateprocess
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com"),  _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.csiamerica.com", IsNullable:=false)>  _
    Partial Public Class advanced
        
        Private control_fileField As advancedControl_file
        
        Private take_screenshots_after_model_run_timeoutsField As yes_no
        
        '''<remarks/>
        Public Property control_file() As advancedControl_file
            Get
                Return Me.control_fileField
            End Get
            Set
                Me.control_fileField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property take_screenshots_after_model_run_timeouts() As yes_no
            Get
                Return Me.take_screenshots_after_model_run_timeoutsField
            End Get
            Set
                Me.take_screenshots_after_model_run_timeoutsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.csiamerica.com")>  _
    Partial Public Class advancedControl_file
        
        Private pathField As path1
        
        '''<remarks/>
        Public Property path() As path1
            Get
                Return Me.pathField
            End Get
            Set
                Me.pathField = value
            End Set
        End Property
    End Class
End Namespace
